(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite2 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite3 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite4 - satellite
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	image8 - mode
	image0 - mode
	infrared3 - mode
	spectrograph9 - mode
	thermograph6 - mode
	thermograph5 - mode
	thermograph7 - mode
	spectrograph1 - mode
	image4 - mode
	spectrograph2 - mode
	star12 - direction
	groundstation7 - direction
	star3 - direction
	groundstation1 - direction
	star10 - direction
	groundstation6 - direction
	groundstation2 - direction
	groundstation14 - direction
	star9 - direction
	groundstation15 - direction
	groundstation5 - direction
	groundstation8 - direction
	groundstation0 - direction
	groundstation13 - direction
	groundstation4 - direction
	groundstation11 - direction
	planet16 - direction
	phenomenon17 - direction
	star18 - direction
	star19 - direction
	planet20 - direction
	phenomenon21 - direction
	phenomenon22 - direction
	phenomenon23 - direction
	star24 - direction
	star25 - direction
	planet26 - direction
	star27 - direction
	phenomenon28 - direction
	phenomenon29 - direction
	planet30 - direction
	phenomenon31 - direction
	phenomenon32 - direction
	phenomenon33 - direction
	phenomenon34 - direction
	phenomenon35 - direction
	star36 - direction
	planet37 - direction
	planet38 - direction
	phenomenon39 - direction
	star40 - direction
	planet41 - direction
)
(:init
	(supports instrument0 spectrograph2)
	(calibration_target instrument0 groundstation11)
	(supports instrument1 image0)
	(supports instrument1 spectrograph2)
	(supports instrument1 image8)
	(calibration_target instrument1 groundstation14)
	(calibration_target instrument1 groundstation0)
	(calibration_target instrument1 star9)
	(calibration_target instrument1 groundstation4)
	(calibration_target instrument1 groundstation8)
	(supports instrument2 spectrograph9)
	(calibration_target instrument2 star12)
	(calibration_target instrument2 groundstation11)
	(calibration_target instrument2 star9)
	(calibration_target instrument2 star10)
	(calibration_target instrument2 groundstation5)
	(supports instrument3 spectrograph9)
	(calibration_target instrument3 groundstation11)
	(calibration_target instrument3 groundstation2)
	(supports instrument4 spectrograph1)
	(supports instrument4 infrared3)
	(supports instrument4 thermograph6)
	(calibration_target instrument4 groundstation1)
	(calibration_target instrument4 groundstation6)
	(supports instrument5 image4)
	(calibration_target instrument5 groundstation4)
	(calibration_target instrument5 star3)
	(supports instrument6 image8)
	(supports instrument6 image0)
	(supports instrument6 spectrograph1)
	(calibration_target instrument6 groundstation14)
	(calibration_target instrument6 groundstation7)
	(calibration_target instrument6 groundstation6)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 planet41)
	(supports instrument7 image8)
	(supports instrument7 spectrograph9)
	(calibration_target instrument7 groundstation7)
	(calibration_target instrument7 star12)
	(calibration_target instrument7 groundstation1)
	(supports instrument8 image4)
	(calibration_target instrument8 star12)
	(supports instrument9 spectrograph9)
	(supports instrument9 thermograph7)
	(calibration_target instrument9 groundstation14)
	(calibration_target instrument9 star12)
	(calibration_target instrument9 groundstation0)
	(calibration_target instrument9 groundstation6)
	(supports instrument10 spectrograph9)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 groundstation2)
	(calibration_target instrument10 groundstation15)
	(calibration_target instrument10 groundstation11)
	(calibration_target instrument10 groundstation14)
	(calibration_target instrument10 star12)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(power_avail satellite1)
	(pointing satellite1 star18)
	(supports instrument11 spectrograph9)
	(calibration_target instrument11 groundstation8)
	(calibration_target instrument11 star10)
	(calibration_target instrument11 groundstation4)
	(supports instrument12 image0)
	(supports instrument12 thermograph6)
	(supports instrument12 spectrograph9)
	(calibration_target instrument12 groundstation14)
	(calibration_target instrument12 groundstation8)
	(supports instrument13 spectrograph2)
	(supports instrument13 infrared3)
	(supports instrument13 image0)
	(calibration_target instrument13 groundstation8)
	(calibration_target instrument13 groundstation13)
	(supports instrument14 image4)
	(supports instrument14 infrared3)
	(supports instrument14 thermograph6)
	(calibration_target instrument14 star10)
	(calibration_target instrument14 groundstation1)
	(calibration_target instrument14 groundstation11)
	(supports instrument15 infrared3)
	(supports instrument15 spectrograph9)
	(supports instrument15 image8)
	(calibration_target instrument15 star12)
	(supports instrument16 image0)
	(supports instrument16 spectrograph2)
	(calibration_target instrument16 groundstation0)
	(supports instrument17 thermograph6)
	(calibration_target instrument17 groundstation7)
	(calibration_target instrument17 groundstation15)
	(supports instrument18 thermograph5)
	(calibration_target instrument18 groundstation5)
	(calibration_target instrument18 groundstation13)
	(calibration_target instrument18 groundstation11)
	(calibration_target instrument18 groundstation2)
	(on_board instrument11 satellite2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(power_avail satellite2)
	(pointing satellite2 groundstation5)
	(supports instrument19 spectrograph1)
	(calibration_target instrument19 star10)
	(calibration_target instrument19 groundstation1)
	(calibration_target instrument19 groundstation7)
	(calibration_target instrument19 groundstation2)
	(supports instrument20 thermograph5)
	(supports instrument20 spectrograph9)
	(supports instrument20 image0)
	(calibration_target instrument20 star12)
	(calibration_target instrument20 groundstation6)
	(calibration_target instrument20 groundstation4)
	(calibration_target instrument20 groundstation5)
	(supports instrument21 image4)
	(calibration_target instrument21 groundstation5)
	(supports instrument22 thermograph7)
	(supports instrument22 infrared3)
	(supports instrument22 image4)
	(calibration_target instrument22 groundstation7)
	(calibration_target instrument22 groundstation15)
	(calibration_target instrument22 groundstation13)
	(calibration_target instrument22 groundstation0)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(power_avail satellite3)
	(pointing satellite3 phenomenon33)
	(supports instrument23 thermograph5)
	(supports instrument23 spectrograph2)
	(supports instrument23 image4)
	(calibration_target instrument23 groundstation7)
	(supports instrument24 thermograph6)
	(calibration_target instrument24 star3)
	(calibration_target instrument24 groundstation7)
	(calibration_target instrument24 groundstation6)
	(supports instrument25 image0)
	(supports instrument25 thermograph5)
	(supports instrument25 spectrograph1)
	(calibration_target instrument25 groundstation1)
	(calibration_target instrument25 groundstation4)
	(supports instrument26 spectrograph9)
	(supports instrument26 thermograph7)
	(calibration_target instrument26 groundstation8)
	(calibration_target instrument26 star10)
	(calibration_target instrument26 groundstation5)
	(supports instrument27 thermograph6)
	(supports instrument27 image0)
	(supports instrument27 infrared3)
	(calibration_target instrument27 groundstation2)
	(calibration_target instrument27 groundstation0)
	(calibration_target instrument27 groundstation6)
	(supports instrument28 spectrograph1)
	(calibration_target instrument28 groundstation14)
	(calibration_target instrument28 groundstation4)
	(calibration_target instrument28 groundstation0)
	(supports instrument29 spectrograph9)
	(supports instrument29 infrared3)
	(supports instrument29 spectrograph2)
	(calibration_target instrument29 groundstation0)
	(calibration_target instrument29 groundstation5)
	(calibration_target instrument29 groundstation15)
	(calibration_target instrument29 groundstation8)
	(calibration_target instrument29 star9)
	(supports instrument30 thermograph7)
	(supports instrument30 thermograph5)
	(supports instrument30 thermograph6)
	(calibration_target instrument30 groundstation8)
	(supports instrument31 image4)
	(supports instrument31 spectrograph1)
	(calibration_target instrument31 groundstation4)
	(calibration_target instrument31 groundstation13)
	(calibration_target instrument31 groundstation0)
	(supports instrument32 spectrograph2)
	(calibration_target instrument32 groundstation11)
	(on_board instrument23 satellite4)
	(on_board instrument24 satellite4)
	(on_board instrument25 satellite4)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(power_avail satellite4)
	(pointing satellite4 groundstation14)
)
(:goal (and
	(pointing satellite0 star10)
	(have_image planet16 thermograph6)
	(have_image planet16 spectrograph2)
	(have_image planet16 spectrograph1)
	(have_image phenomenon17 image0)
	(have_image phenomenon17 image4)
	(have_image phenomenon17 thermograph6)
	(have_image star18 thermograph5)
	(have_image star18 infrared3)
	(have_image planet20 spectrograph2)
	(have_image phenomenon22 spectrograph2)
	(have_image phenomenon22 thermograph6)
	(have_image phenomenon22 thermograph5)
	(have_image phenomenon23 spectrograph2)
	(have_image phenomenon23 image0)
	(have_image phenomenon23 spectrograph9)
	(have_image star24 spectrograph2)
	(have_image star25 thermograph6)
	(have_image star25 image4)
	(have_image planet26 image0)
	(have_image star27 spectrograph2)
	(have_image phenomenon29 spectrograph2)
	(have_image phenomenon29 thermograph7)
	(have_image planet30 spectrograph2)
	(have_image phenomenon31 spectrograph9)
	(have_image phenomenon31 thermograph5)
	(have_image phenomenon31 thermograph6)
	(have_image phenomenon32 spectrograph1)
	(have_image phenomenon32 spectrograph9)
	(have_image phenomenon33 image0)
	(have_image phenomenon34 spectrograph1)
	(have_image phenomenon34 thermograph5)
	(have_image phenomenon34 spectrograph9)
	(have_image star36 thermograph6)
	(have_image planet37 spectrograph1)
	(have_image planet37 thermograph6)
	(have_image planet37 infrared3)
	(have_image planet38 thermograph6)
	(have_image planet38 thermograph7)
	(have_image phenomenon39 thermograph6)
	(have_image phenomenon39 spectrograph9)
	(have_image phenomenon39 spectrograph1)
	(have_image star40 image8)
	(have_image star40 image4)
	(have_image planet41 infrared3)
	(have_image planet41 thermograph6)
	(have_image planet41 thermograph7)
))
(:metric minimize (total-time))

)
