(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite5 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite6 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	infrared3 - mode
	image0 - mode
	spectrograph2 - mode
	image4 - mode
	thermograph5 - mode
	spectrograph1 - mode
	star14 - direction
	groundstation11 - direction
	groundstation12 - direction
	groundstation8 - direction
	groundstation4 - direction
	groundstation1 - direction
	groundstation0 - direction
	star2 - direction
	groundstation17 - direction
	star5 - direction
	groundstation10 - direction
	star15 - direction
	star9 - direction
	star7 - direction
	star6 - direction
	star13 - direction
	groundstation3 - direction
	star16 - direction
	star18 - direction
	planet19 - direction
	planet20 - direction
	star21 - direction
	phenomenon22 - direction
	phenomenon23 - direction
	planet24 - direction
	star25 - direction
	star26 - direction
	star27 - direction
	planet28 - direction
	star29 - direction
	star30 - direction
	phenomenon31 - direction
	planet32 - direction
	star33 - direction
	planet34 - direction
	star35 - direction
	star36 - direction
	star37 - direction
	planet38 - direction
	star39 - direction
	planet40 - direction
	phenomenon41 - direction
	planet42 - direction
	planet43 - direction
	star44 - direction
	phenomenon45 - direction
)
(:init
	(supports instrument0 thermograph5)
	(supports instrument0 image0)
	(calibration_target instrument0 groundstation4)
	(calibration_target instrument0 groundstation1)
	(calibration_target instrument0 groundstation10)
	(calibration_target instrument0 star2)
	(calibration_target instrument0 groundstation17)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 planet40)
	(supports instrument1 infrared3)
	(supports instrument1 image4)
	(calibration_target instrument1 groundstation11)
	(calibration_target instrument1 star6)
	(supports instrument2 image0)
	(supports instrument2 spectrograph2)
	(supports instrument2 infrared3)
	(calibration_target instrument2 groundstation10)
	(calibration_target instrument2 groundstation8)
	(calibration_target instrument2 star15)
	(supports instrument3 infrared3)
	(supports instrument3 thermograph5)
	(supports instrument3 spectrograph1)
	(calibration_target instrument3 groundstation17)
	(calibration_target instrument3 groundstation3)
	(calibration_target instrument3 star16)
	(supports instrument4 infrared3)
	(supports instrument4 image0)
	(calibration_target instrument4 groundstation12)
	(calibration_target instrument4 groundstation17)
	(calibration_target instrument4 groundstation10)
	(calibration_target instrument4 groundstation4)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 groundstation10)
	(supports instrument5 image4)
	(supports instrument5 image0)
	(calibration_target instrument5 star2)
	(calibration_target instrument5 star7)
	(calibration_target instrument5 star14)
	(calibration_target instrument5 star15)
	(calibration_target instrument5 star16)
	(supports instrument6 spectrograph1)
	(calibration_target instrument6 groundstation0)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 star30)
	(supports instrument7 infrared3)
	(supports instrument7 spectrograph2)
	(supports instrument7 thermograph5)
	(calibration_target instrument7 groundstation10)
	(calibration_target instrument7 groundstation1)
	(calibration_target instrument7 groundstation3)
	(calibration_target instrument7 star6)
	(supports instrument8 spectrograph2)
	(calibration_target instrument8 star7)
	(calibration_target instrument8 groundstation4)
	(calibration_target instrument8 groundstation3)
	(calibration_target instrument8 star2)
	(calibration_target instrument8 star15)
	(calibration_target instrument8 star5)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 planet28)
	(supports instrument9 spectrograph1)
	(supports instrument9 spectrograph2)
	(supports instrument9 image4)
	(calibration_target instrument9 groundstation0)
	(calibration_target instrument9 groundstation4)
	(calibration_target instrument9 groundstation11)
	(calibration_target instrument9 star6)
	(supports instrument10 infrared3)
	(calibration_target instrument10 star7)
	(calibration_target instrument10 star14)
	(calibration_target instrument10 groundstation8)
	(supports instrument11 spectrograph2)
	(supports instrument11 image0)
	(supports instrument11 infrared3)
	(calibration_target instrument11 groundstation11)
	(calibration_target instrument11 star16)
	(supports instrument12 infrared3)
	(calibration_target instrument12 groundstation3)
	(calibration_target instrument12 groundstation12)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 star44)
	(supports instrument13 image0)
	(calibration_target instrument13 star2)
	(calibration_target instrument13 star14)
	(supports instrument14 spectrograph2)
	(supports instrument14 thermograph5)
	(supports instrument14 image4)
	(calibration_target instrument14 groundstation4)
	(calibration_target instrument14 groundstation12)
	(calibration_target instrument14 groundstation11)
	(calibration_target instrument14 groundstation8)
	(supports instrument15 image0)
	(supports instrument15 spectrograph2)
	(calibration_target instrument15 groundstation8)
	(calibration_target instrument15 groundstation17)
	(calibration_target instrument15 star15)
	(calibration_target instrument15 star13)
	(calibration_target instrument15 star2)
	(calibration_target instrument15 star7)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(power_avail satellite5)
	(pointing satellite5 phenomenon22)
	(supports instrument16 thermograph5)
	(calibration_target instrument16 groundstation17)
	(calibration_target instrument16 groundstation4)
	(supports instrument17 image0)
	(calibration_target instrument17 groundstation17)
	(calibration_target instrument17 star2)
	(calibration_target instrument17 groundstation0)
	(calibration_target instrument17 groundstation1)
	(supports instrument18 thermograph5)
	(supports instrument18 image4)
	(supports instrument18 spectrograph2)
	(calibration_target instrument18 groundstation3)
	(calibration_target instrument18 star9)
	(calibration_target instrument18 star15)
	(calibration_target instrument18 groundstation10)
	(calibration_target instrument18 star5)
	(calibration_target instrument18 star7)
	(supports instrument19 spectrograph1)
	(calibration_target instrument19 star16)
	(calibration_target instrument19 groundstation3)
	(calibration_target instrument19 star13)
	(calibration_target instrument19 star6)
	(calibration_target instrument19 star7)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(power_avail satellite6)
	(pointing satellite6 star7)
)
(:goal (and
	(pointing satellite1 star9)
	(pointing satellite4 planet34)
	(have_image star18 thermograph5)
	(have_image planet19 image4)
	(have_image planet19 thermograph5)
	(have_image planet20 image4)
	(have_image star21 image0)
	(have_image star21 spectrograph2)
	(have_image phenomenon22 infrared3)
	(have_image phenomenon23 spectrograph2)
	(have_image phenomenon23 image4)
	(have_image star25 spectrograph2)
	(have_image star26 image0)
	(have_image star27 image0)
	(have_image planet28 thermograph5)
	(have_image planet28 spectrograph2)
	(have_image star29 image0)
	(have_image star30 spectrograph2)
	(have_image star30 thermograph5)
	(have_image planet32 image0)
	(have_image star33 spectrograph2)
	(have_image star33 thermograph5)
	(have_image planet34 infrared3)
	(have_image planet34 image0)
	(have_image star35 image4)
	(have_image star35 spectrograph1)
	(have_image star37 thermograph5)
	(have_image planet38 thermograph5)
	(have_image planet38 image0)
	(have_image planet40 infrared3)
	(have_image planet40 spectrograph2)
	(have_image phenomenon41 thermograph5)
	(have_image phenomenon41 spectrograph2)
	(have_image planet42 infrared3)
	(have_image planet42 image4)
	(have_image planet43 spectrograph1)
	(have_image planet43 spectrograph2)
	(have_image star44 infrared3)
	(have_image phenomenon45 image0)
))
(:metric minimize (total-time))

)
