(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite1 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite2 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite3 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	satellite4 - satellite
	instrument40 - instrument
	satellite5 - satellite
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	satellite6 - satellite
	instrument48 - instrument
	instrument49 - instrument
	instrument50 - instrument
	instrument51 - instrument
	instrument52 - instrument
	instrument53 - instrument
	instrument54 - instrument
	instrument55 - instrument
	instrument56 - instrument
	instrument57 - instrument
	instrument58 - instrument
	image4 - mode
	thermograph12 - mode
	spectrograph13 - mode
	infrared3 - mode
	thermograph5 - mode
	spectrograph2 - mode
	image0 - mode
	spectrograph1 - mode
	image8 - mode
	image11 - mode
	thermograph7 - mode
	spectrograph9 - mode
	thermograph6 - mode
	thermograph10 - mode
	groundstation1 - direction
	star3 - direction
	star12 - direction
	star5 - direction
	star7 - direction
	groundstation15 - direction
	groundstation22 - direction
	star10 - direction
	groundstation9 - direction
	star14 - direction
	star4 - direction
	star16 - direction
	groundstation18 - direction
	star21 - direction
	groundstation2 - direction
	groundstation20 - direction
	star19 - direction
	star13 - direction
	star0 - direction
	groundstation17 - direction
	star8 - direction
	groundstation6 - direction
	star11 - direction
	phenomenon23 - direction
	planet24 - direction
	planet25 - direction
	planet26 - direction
	planet27 - direction
	planet28 - direction
	planet29 - direction
	phenomenon30 - direction
	star31 - direction
	phenomenon32 - direction
	planet33 - direction
	phenomenon34 - direction
	star35 - direction
	phenomenon36 - direction
	planet37 - direction
	phenomenon38 - direction
	phenomenon39 - direction
	star40 - direction
	phenomenon41 - direction
	phenomenon42 - direction
	star43 - direction
	planet44 - direction
	star45 - direction
	star46 - direction
	star47 - direction
	phenomenon48 - direction
	star49 - direction
	star50 - direction
	star51 - direction
	planet52 - direction
	phenomenon53 - direction
	phenomenon54 - direction
	star55 - direction
)
(:init
	(supports instrument0 thermograph5)
	(supports instrument0 thermograph6)
	(calibration_target instrument0 star11)
	(calibration_target instrument0 groundstation18)
	(calibration_target instrument0 groundstation1)
	(calibration_target instrument0 groundstation22)
	(calibration_target instrument0 groundstation20)
	(supports instrument1 spectrograph9)
	(supports instrument1 image11)
	(supports instrument1 image0)
	(calibration_target instrument1 star10)
	(calibration_target instrument1 star11)
	(calibration_target instrument1 groundstation15)
	(supports instrument2 image4)
	(supports instrument2 image11)
	(calibration_target instrument2 star10)
	(supports instrument3 thermograph12)
	(supports instrument3 image8)
	(calibration_target instrument3 star16)
	(calibration_target instrument3 star7)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 star21)
	(calibration_target instrument4 groundstation22)
	(supports instrument5 spectrograph13)
	(supports instrument5 image11)
	(supports instrument5 thermograph10)
	(calibration_target instrument5 groundstation1)
	(calibration_target instrument5 star11)
	(calibration_target instrument5 star10)
	(calibration_target instrument5 star13)
	(calibration_target instrument5 groundstation2)
	(calibration_target instrument5 star4)
	(supports instrument6 thermograph5)
	(supports instrument6 image11)
	(supports instrument6 thermograph6)
	(calibration_target instrument6 star8)
	(calibration_target instrument6 groundstation2)
	(calibration_target instrument6 star13)
	(calibration_target instrument6 groundstation20)
	(calibration_target instrument6 star3)
	(supports instrument7 image8)
	(calibration_target instrument7 star8)
	(supports instrument8 thermograph6)
	(supports instrument8 spectrograph1)
	(supports instrument8 thermograph5)
	(calibration_target instrument8 star14)
	(calibration_target instrument8 star13)
	(calibration_target instrument8 star0)
	(calibration_target instrument8 groundstation2)
	(calibration_target instrument8 groundstation1)
	(calibration_target instrument8 star4)
	(calibration_target instrument8 groundstation22)
	(supports instrument9 image8)
	(calibration_target instrument9 star21)
	(supports instrument10 image4)
	(supports instrument10 thermograph6)
	(supports instrument10 image0)
	(calibration_target instrument10 star13)
	(calibration_target instrument10 star16)
	(calibration_target instrument10 star19)
	(calibration_target instrument10 star8)
	(supports instrument11 image11)
	(calibration_target instrument11 star19)
	(calibration_target instrument11 groundstation18)
	(supports instrument12 image8)
	(supports instrument12 thermograph6)
	(supports instrument12 thermograph5)
	(calibration_target instrument12 groundstation20)
	(calibration_target instrument12 groundstation18)
	(calibration_target instrument12 star5)
	(supports instrument13 image11)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 groundstation15)
	(calibration_target instrument13 star4)
	(calibration_target instrument13 groundstation9)
	(calibration_target instrument13 groundstation2)
	(calibration_target instrument13 star12)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(on_board instrument9 satellite0)
	(on_board instrument10 satellite0)
	(on_board instrument11 satellite0)
	(on_board instrument12 satellite0)
	(on_board instrument13 satellite0)
	(power_avail satellite0)
	(pointing satellite0 planet33)
	(supports instrument14 image0)
	(calibration_target instrument14 groundstation1)
	(calibration_target instrument14 groundstation15)
	(calibration_target instrument14 groundstation20)
	(calibration_target instrument14 star0)
	(calibration_target instrument14 star8)
	(calibration_target instrument14 star10)
	(supports instrument15 thermograph5)
	(calibration_target instrument15 star11)
	(calibration_target instrument15 star4)
	(calibration_target instrument15 star3)
	(calibration_target instrument15 star10)
	(supports instrument16 spectrograph9)
	(supports instrument16 thermograph5)
	(calibration_target instrument16 star5)
	(calibration_target instrument16 star11)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(on_board instrument16 satellite1)
	(power_avail satellite1)
	(pointing satellite1 star16)
	(supports instrument17 infrared3)
	(calibration_target instrument17 groundstation2)
	(calibration_target instrument17 star21)
	(calibration_target instrument17 groundstation9)
	(calibration_target instrument17 star7)
	(supports instrument18 spectrograph9)
	(supports instrument18 thermograph5)
	(calibration_target instrument18 groundstation15)
	(calibration_target instrument18 star12)
	(supports instrument19 thermograph5)
	(supports instrument19 thermograph6)
	(calibration_target instrument19 star16)
	(calibration_target instrument19 star21)
	(calibration_target instrument19 groundstation15)
	(supports instrument20 spectrograph13)
	(supports instrument20 thermograph12)
	(calibration_target instrument20 groundstation9)
	(calibration_target instrument20 star5)
	(calibration_target instrument20 groundstation15)
	(calibration_target instrument20 star19)
	(calibration_target instrument20 groundstation2)
	(supports instrument21 image11)
	(supports instrument21 image0)
	(calibration_target instrument21 groundstation15)
	(supports instrument22 infrared3)
	(supports instrument22 image0)
	(calibration_target instrument22 star16)
	(supports instrument23 spectrograph13)
	(supports instrument23 image8)
	(supports instrument23 spectrograph1)
	(calibration_target instrument23 star19)
	(calibration_target instrument23 star21)
	(calibration_target instrument23 groundstation22)
	(calibration_target instrument23 star10)
	(calibration_target instrument23 star3)
	(calibration_target instrument23 star5)
	(calibration_target instrument23 star8)
	(supports instrument24 spectrograph2)
	(supports instrument24 image11)
	(supports instrument24 image8)
	(calibration_target instrument24 groundstation2)
	(calibration_target instrument24 star11)
	(calibration_target instrument24 star7)
	(calibration_target instrument24 star12)
	(calibration_target instrument24 groundstation9)
	(calibration_target instrument24 star13)
	(calibration_target instrument24 groundstation15)
	(supports instrument25 thermograph10)
	(calibration_target instrument25 groundstation9)
	(supports instrument26 image0)
	(supports instrument26 thermograph12)
	(supports instrument26 spectrograph1)
	(calibration_target instrument26 groundstation17)
	(calibration_target instrument26 groundstation22)
	(calibration_target instrument26 star10)
	(calibration_target instrument26 groundstation18)
	(calibration_target instrument26 star0)
	(calibration_target instrument26 star5)
	(supports instrument27 spectrograph2)
	(supports instrument27 image11)
	(supports instrument27 thermograph10)
	(calibration_target instrument27 star19)
	(calibration_target instrument27 groundstation2)
	(calibration_target instrument27 groundstation1)
	(calibration_target instrument27 groundstation22)
	(supports instrument28 thermograph10)
	(supports instrument28 spectrograph2)
	(supports instrument28 spectrograph9)
	(calibration_target instrument28 star5)
	(calibration_target instrument28 star8)
	(calibration_target instrument28 groundstation2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(on_board instrument22 satellite2)
	(on_board instrument23 satellite2)
	(on_board instrument24 satellite2)
	(on_board instrument25 satellite2)
	(on_board instrument26 satellite2)
	(on_board instrument27 satellite2)
	(on_board instrument28 satellite2)
	(power_avail satellite2)
	(pointing satellite2 groundstation20)
	(supports instrument29 spectrograph1)
	(supports instrument29 infrared3)
	(supports instrument29 thermograph12)
	(calibration_target instrument29 groundstation1)
	(supports instrument30 thermograph10)
	(calibration_target instrument30 groundstation9)
	(calibration_target instrument30 groundstation17)
	(calibration_target instrument30 groundstation15)
	(calibration_target instrument30 star21)
	(calibration_target instrument30 star7)
	(calibration_target instrument30 star3)
	(calibration_target instrument30 groundstation18)
	(supports instrument31 thermograph12)
	(supports instrument31 image0)
	(supports instrument31 image4)
	(calibration_target instrument31 star11)
	(calibration_target instrument31 star21)
	(calibration_target instrument31 star5)
	(calibration_target instrument31 groundstation15)
	(calibration_target instrument31 star16)
	(calibration_target instrument31 star13)
	(supports instrument32 spectrograph9)
	(supports instrument32 thermograph10)
	(supports instrument32 thermograph7)
	(calibration_target instrument32 groundstation6)
	(calibration_target instrument32 star3)
	(calibration_target instrument32 star13)
	(calibration_target instrument32 star14)
	(calibration_target instrument32 star19)
	(calibration_target instrument32 star8)
	(calibration_target instrument32 star12)
	(supports instrument33 thermograph7)
	(supports instrument33 image0)
	(supports instrument33 thermograph12)
	(calibration_target instrument33 groundstation6)
	(supports instrument34 spectrograph2)
	(calibration_target instrument34 star14)
	(calibration_target instrument34 star12)
	(calibration_target instrument34 groundstation15)
	(calibration_target instrument34 groundstation2)
	(calibration_target instrument34 groundstation9)
	(calibration_target instrument34 star5)
	(calibration_target instrument34 star10)
	(supports instrument35 image4)
	(calibration_target instrument35 groundstation17)
	(calibration_target instrument35 groundstation22)
	(calibration_target instrument35 star13)
	(calibration_target instrument35 star8)
	(supports instrument36 spectrograph13)
	(supports instrument36 image0)
	(calibration_target instrument36 star5)
	(calibration_target instrument36 star10)
	(calibration_target instrument36 star16)
	(calibration_target instrument36 star11)
	(supports instrument37 spectrograph1)
	(supports instrument37 image0)
	(supports instrument37 thermograph7)
	(calibration_target instrument37 groundstation6)
	(calibration_target instrument37 groundstation20)
	(calibration_target instrument37 star8)
	(calibration_target instrument37 groundstation9)
	(calibration_target instrument37 star12)
	(calibration_target instrument37 groundstation18)
	(calibration_target instrument37 star11)
	(supports instrument38 spectrograph2)
	(supports instrument38 spectrograph9)
	(calibration_target instrument38 star19)
	(calibration_target instrument38 star0)
	(calibration_target instrument38 groundstation15)
	(calibration_target instrument38 star10)
	(calibration_target instrument38 star3)
	(calibration_target instrument38 groundstation20)
	(calibration_target instrument38 groundstation22)
	(supports instrument39 thermograph12)
	(supports instrument39 image0)
	(calibration_target instrument39 star8)
	(calibration_target instrument39 groundstation18)
	(calibration_target instrument39 groundstation9)
	(calibration_target instrument39 star13)
	(calibration_target instrument39 star10)
	(calibration_target instrument39 star16)
	(calibration_target instrument39 groundstation17)
	(on_board instrument29 satellite3)
	(on_board instrument30 satellite3)
	(on_board instrument31 satellite3)
	(on_board instrument32 satellite3)
	(on_board instrument33 satellite3)
	(on_board instrument34 satellite3)
	(on_board instrument35 satellite3)
	(on_board instrument36 satellite3)
	(on_board instrument37 satellite3)
	(on_board instrument38 satellite3)
	(on_board instrument39 satellite3)
	(power_avail satellite3)
	(pointing satellite3 star40)
	(supports instrument40 thermograph12)
	(supports instrument40 spectrograph2)
	(supports instrument40 thermograph5)
	(calibration_target instrument40 groundstation2)
	(calibration_target instrument40 star3)
	(calibration_target instrument40 star14)
	(calibration_target instrument40 star8)
	(calibration_target instrument40 groundstation22)
	(calibration_target instrument40 star10)
	(on_board instrument40 satellite4)
	(power_avail satellite4)
	(pointing satellite4 planet29)
	(supports instrument41 thermograph7)
	(calibration_target instrument41 star21)
	(supports instrument42 image11)
	(calibration_target instrument42 star12)
	(calibration_target instrument42 groundstation1)
	(calibration_target instrument42 star16)
	(supports instrument43 thermograph10)
	(calibration_target instrument43 star4)
	(calibration_target instrument43 star3)
	(calibration_target instrument43 groundstation18)
	(calibration_target instrument43 groundstation6)
	(supports instrument44 infrared3)
	(supports instrument44 image11)
	(supports instrument44 image8)
	(calibration_target instrument44 star13)
	(calibration_target instrument44 star19)
	(calibration_target instrument44 star4)
	(calibration_target instrument44 star8)
	(supports instrument45 infrared3)
	(supports instrument45 thermograph7)
	(supports instrument45 image0)
	(calibration_target instrument45 star7)
	(calibration_target instrument45 star16)
	(calibration_target instrument45 groundstation15)
	(calibration_target instrument45 groundstation9)
	(calibration_target instrument45 star5)
	(calibration_target instrument45 groundstation17)
	(calibration_target instrument45 star13)
	(supports instrument46 spectrograph2)
	(calibration_target instrument46 star13)
	(calibration_target instrument46 star5)
	(calibration_target instrument46 groundstation9)
	(calibration_target instrument46 star4)
	(supports instrument47 spectrograph1)
	(supports instrument47 thermograph6)
	(supports instrument47 image0)
	(calibration_target instrument47 star11)
	(calibration_target instrument47 groundstation15)
	(calibration_target instrument47 star21)
	(calibration_target instrument47 groundstation22)
	(calibration_target instrument47 star5)
	(calibration_target instrument47 star12)
	(on_board instrument41 satellite5)
	(on_board instrument42 satellite5)
	(on_board instrument43 satellite5)
	(on_board instrument44 satellite5)
	(on_board instrument45 satellite5)
	(on_board instrument46 satellite5)
	(on_board instrument47 satellite5)
	(power_avail satellite5)
	(pointing satellite5 star46)
	(supports instrument48 thermograph12)
	(supports instrument48 image8)
	(supports instrument48 spectrograph1)
	(calibration_target instrument48 star13)
	(calibration_target instrument48 star0)
	(calibration_target instrument48 star7)
	(calibration_target instrument48 groundstation20)
	(calibration_target instrument48 star14)
	(supports instrument49 image8)
	(calibration_target instrument49 groundstation15)
	(calibration_target instrument49 groundstation20)
	(calibration_target instrument49 star16)
	(calibration_target instrument49 groundstation17)
	(supports instrument50 thermograph5)
	(calibration_target instrument50 star11)
	(supports instrument51 thermograph5)
	(supports instrument51 thermograph7)
	(supports instrument51 spectrograph1)
	(calibration_target instrument51 groundstation6)
	(calibration_target instrument51 star16)
	(calibration_target instrument51 star8)
	(calibration_target instrument51 groundstation18)
	(calibration_target instrument51 groundstation15)
	(supports instrument52 infrared3)
	(supports instrument52 thermograph6)
	(calibration_target instrument52 star4)
	(supports instrument53 infrared3)
	(supports instrument53 spectrograph13)
	(calibration_target instrument53 star19)
	(calibration_target instrument53 groundstation9)
	(calibration_target instrument53 star10)
	(calibration_target instrument53 groundstation22)
	(calibration_target instrument53 star16)
	(calibration_target instrument53 groundstation2)
	(supports instrument54 thermograph5)
	(supports instrument54 thermograph7)
	(calibration_target instrument54 star14)
	(calibration_target instrument54 groundstation6)
	(calibration_target instrument54 groundstation18)
	(calibration_target instrument54 groundstation2)
	(supports instrument55 spectrograph2)
	(calibration_target instrument55 star4)
	(calibration_target instrument55 star0)
	(supports instrument56 spectrograph1)
	(supports instrument56 image0)
	(calibration_target instrument56 star11)
	(calibration_target instrument56 groundstation20)
	(calibration_target instrument56 groundstation2)
	(calibration_target instrument56 star21)
	(calibration_target instrument56 groundstation18)
	(calibration_target instrument56 star16)
	(supports instrument57 thermograph7)
	(supports instrument57 image11)
	(supports instrument57 image8)
	(calibration_target instrument57 star13)
	(calibration_target instrument57 star19)
	(calibration_target instrument57 star0)
	(supports instrument58 thermograph10)
	(supports instrument58 thermograph6)
	(supports instrument58 spectrograph9)
	(calibration_target instrument58 star11)
	(calibration_target instrument58 groundstation6)
	(calibration_target instrument58 star8)
	(calibration_target instrument58 groundstation17)
	(calibration_target instrument58 star0)
	(on_board instrument48 satellite6)
	(on_board instrument49 satellite6)
	(on_board instrument50 satellite6)
	(on_board instrument51 satellite6)
	(on_board instrument52 satellite6)
	(on_board instrument53 satellite6)
	(on_board instrument54 satellite6)
	(on_board instrument55 satellite6)
	(on_board instrument56 satellite6)
	(on_board instrument57 satellite6)
	(on_board instrument58 satellite6)
	(power_avail satellite6)
	(pointing satellite6 planet37)
)
(:goal (and
	(pointing satellite1 star35)
	(pointing satellite2 groundstation15)
	(pointing satellite3 phenomenon36)
	(pointing satellite4 phenomenon23)
	(pointing satellite5 star35)
	(have_image phenomenon23 spectrograph1)
	(have_image phenomenon23 spectrograph2)
	(have_image phenomenon23 image11)
	(have_image planet24 thermograph12)
	(have_image planet24 image4)
	(have_image planet24 thermograph7)
	(have_image planet25 image0)
	(have_image planet25 thermograph6)
	(have_image planet25 spectrograph13)
	(have_image planet25 image4)
	(have_image planet26 image8)
	(have_image planet27 spectrograph13)
	(have_image planet27 thermograph5)
	(have_image planet28 image4)
	(have_image planet29 spectrograph9)
	(have_image planet29 infrared3)
	(have_image phenomenon30 spectrograph13)
	(have_image phenomenon30 spectrograph2)
	(have_image phenomenon30 image0)
	(have_image phenomenon30 thermograph5)
	(have_image star31 thermograph10)
	(have_image star31 infrared3)
	(have_image star31 thermograph7)
	(have_image star31 thermograph6)
	(have_image phenomenon32 thermograph7)
	(have_image phenomenon32 thermograph12)
	(have_image phenomenon32 thermograph5)
	(have_image phenomenon32 thermograph10)
	(have_image phenomenon34 image8)
	(have_image star35 spectrograph1)
	(have_image star35 spectrograph13)
	(have_image star35 spectrograph9)
	(have_image star35 image11)
	(have_image phenomenon36 thermograph5)
	(have_image planet37 spectrograph13)
	(have_image planet37 image0)
	(have_image phenomenon38 image4)
	(have_image phenomenon38 thermograph6)
	(have_image phenomenon38 infrared3)
	(have_image phenomenon38 spectrograph2)
	(have_image phenomenon39 spectrograph13)
	(have_image phenomenon39 thermograph12)
	(have_image phenomenon39 spectrograph9)
	(have_image phenomenon39 image8)
	(have_image star40 thermograph12)
	(have_image star40 spectrograph2)
	(have_image phenomenon42 image4)
	(have_image phenomenon42 infrared3)
	(have_image phenomenon42 thermograph6)
	(have_image phenomenon42 thermograph5)
	(have_image star43 infrared3)
	(have_image star43 image0)
	(have_image star43 thermograph10)
	(have_image planet44 image8)
	(have_image planet44 spectrograph13)
	(have_image planet44 thermograph12)
	(have_image star45 infrared3)
	(have_image star45 spectrograph2)
	(have_image star46 infrared3)
	(have_image star49 infrared3)
	(have_image star50 image4)
	(have_image star50 spectrograph9)
	(have_image star50 thermograph12)
	(have_image star50 infrared3)
	(have_image star51 image4)
	(have_image star51 spectrograph2)
	(have_image star51 thermograph7)
	(have_image star51 spectrograph1)
	(have_image planet52 thermograph10)
	(have_image planet52 infrared3)
	(have_image planet52 image4)
	(have_image planet52 image0)
	(have_image phenomenon53 image8)
	(have_image phenomenon53 infrared3)
	(have_image phenomenon53 image11)
	(have_image phenomenon53 thermograph6)
	(have_image phenomenon54 spectrograph1)
	(have_image star55 spectrograph13)
	(have_image star55 image8)
))
(:metric minimize (total-time))

)
