(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite4 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite5 - satellite
	instrument13 - instrument
	instrument14 - instrument
	satellite6 - satellite
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	image0 - mode
	image4 - mode
	spectrograph2 - mode
	infrared3 - mode
	spectrograph1 - mode
	groundstation5 - direction
	groundstation7 - direction
	groundstation11 - direction
	star1 - direction
	groundstation2 - direction
	groundstation12 - direction
	groundstation3 - direction
	groundstation13 - direction
	star10 - direction
	star6 - direction
	groundstation8 - direction
	groundstation14 - direction
	groundstation0 - direction
	groundstation9 - direction
	star4 - direction
	planet15 - direction
	phenomenon16 - direction
	phenomenon17 - direction
	planet18 - direction
	phenomenon19 - direction
	planet20 - direction
	planet21 - direction
	phenomenon22 - direction
	planet23 - direction
	planet24 - direction
	planet25 - direction
	planet26 - direction
	planet27 - direction
	star28 - direction
	phenomenon29 - direction
	planet30 - direction
	planet31 - direction
	star32 - direction
	planet33 - direction
	planet34 - direction
	star35 - direction
	phenomenon36 - direction
	planet37 - direction
	star38 - direction
	phenomenon39 - direction
)
(:init
	(supports instrument0 spectrograph2)
	(supports instrument0 infrared3)
	(calibration_target instrument0 groundstation11)
	(calibration_target instrument0 groundstation0)
	(calibration_target instrument0 star1)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 planet18)
	(supports instrument1 image4)
	(supports instrument1 image0)
	(calibration_target instrument1 groundstation3)
	(calibration_target instrument1 star1)
	(calibration_target instrument1 groundstation14)
	(supports instrument2 image4)
	(supports instrument2 infrared3)
	(supports instrument2 image0)
	(calibration_target instrument2 groundstation12)
	(calibration_target instrument2 groundstation9)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 star4)
	(supports instrument3 spectrograph2)
	(supports instrument3 image0)
	(calibration_target instrument3 groundstation0)
	(calibration_target instrument3 groundstation9)
	(calibration_target instrument3 groundstation12)
	(calibration_target instrument3 groundstation2)
	(calibration_target instrument3 groundstation7)
	(supports instrument4 image4)
	(supports instrument4 image0)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 groundstation12)
	(calibration_target instrument4 groundstation9)
	(supports instrument5 spectrograph2)
	(calibration_target instrument5 groundstation3)
	(calibration_target instrument5 groundstation5)
	(supports instrument6 image4)
	(calibration_target instrument6 star1)
	(calibration_target instrument6 groundstation2)
	(supports instrument7 infrared3)
	(supports instrument7 spectrograph2)
	(calibration_target instrument7 groundstation2)
	(calibration_target instrument7 groundstation5)
	(calibration_target instrument7 groundstation14)
	(calibration_target instrument7 groundstation9)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 planet34)
	(supports instrument8 spectrograph2)
	(calibration_target instrument8 groundstation13)
	(calibration_target instrument8 groundstation2)
	(calibration_target instrument8 groundstation3)
	(calibration_target instrument8 star6)
	(supports instrument9 image0)
	(supports instrument9 image4)
	(calibration_target instrument9 groundstation13)
	(calibration_target instrument9 groundstation11)
	(supports instrument10 image0)
	(supports instrument10 spectrograph2)
	(supports instrument10 spectrograph1)
	(calibration_target instrument10 groundstation11)
	(calibration_target instrument10 groundstation12)
	(calibration_target instrument10 groundstation3)
	(calibration_target instrument10 groundstation8)
	(calibration_target instrument10 star10)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(power_avail satellite3)
	(pointing satellite3 planet18)
	(supports instrument11 spectrograph2)
	(supports instrument11 spectrograph1)
	(calibration_target instrument11 star4)
	(calibration_target instrument11 groundstation13)
	(calibration_target instrument11 groundstation7)
	(calibration_target instrument11 star1)
	(supports instrument12 spectrograph2)
	(calibration_target instrument12 groundstation11)
	(calibration_target instrument12 groundstation7)
	(calibration_target instrument12 groundstation3)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 planet33)
	(supports instrument13 spectrograph1)
	(supports instrument13 image0)
	(calibration_target instrument13 star6)
	(calibration_target instrument13 groundstation2)
	(calibration_target instrument13 star1)
	(calibration_target instrument13 star10)
	(calibration_target instrument13 groundstation11)
	(supports instrument14 spectrograph1)
	(supports instrument14 spectrograph2)
	(supports instrument14 infrared3)
	(calibration_target instrument14 groundstation12)
	(calibration_target instrument14 groundstation2)
	(calibration_target instrument14 groundstation13)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(power_avail satellite5)
	(pointing satellite5 groundstation12)
	(supports instrument15 image4)
	(supports instrument15 infrared3)
	(supports instrument15 image0)
	(calibration_target instrument15 groundstation13)
	(calibration_target instrument15 groundstation3)
	(supports instrument16 spectrograph1)
	(supports instrument16 spectrograph2)
	(supports instrument16 infrared3)
	(calibration_target instrument16 groundstation0)
	(calibration_target instrument16 groundstation14)
	(calibration_target instrument16 groundstation8)
	(calibration_target instrument16 star6)
	(calibration_target instrument16 star10)
	(supports instrument17 spectrograph1)
	(supports instrument17 infrared3)
	(calibration_target instrument17 star4)
	(calibration_target instrument17 groundstation9)
	(calibration_target instrument17 groundstation0)
	(on_board instrument15 satellite6)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 planet33)
)
(:goal (and
	(pointing satellite4 planet31)
	(pointing satellite5 planet30)
	(pointing satellite6 groundstation9)
	(have_image planet15 infrared3)
	(have_image phenomenon16 image0)
	(have_image phenomenon17 spectrograph2)
	(have_image planet18 spectrograph1)
	(have_image phenomenon19 image0)
	(have_image planet20 spectrograph1)
	(have_image planet21 spectrograph2)
	(have_image phenomenon22 image4)
	(have_image planet24 spectrograph2)
	(have_image planet25 spectrograph1)
	(have_image planet26 image4)
	(have_image planet27 spectrograph1)
	(have_image star28 image4)
	(have_image phenomenon29 spectrograph1)
	(have_image planet30 spectrograph1)
	(have_image planet31 spectrograph2)
	(have_image star32 spectrograph1)
	(have_image planet33 spectrograph2)
	(have_image star35 infrared3)
	(have_image phenomenon36 spectrograph1)
	(have_image planet37 infrared3)
	(have_image star38 image0)
	(have_image phenomenon39 image0)
))
(:metric minimize (total-time))

)
