(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	image4 - mode
	spectrograph2 - mode
	image0 - mode
	spectrograph1 - mode
	infrared3 - mode
	groundstation0 - direction
	star1 - direction
	groundstation9 - direction
	star6 - direction
	star4 - direction
	groundstation5 - direction
	groundstation2 - direction
	groundstation3 - direction
	groundstation7 - direction
	groundstation8 - direction
	star10 - direction
	planet11 - direction
	star12 - direction
	planet13 - direction
	phenomenon14 - direction
	planet15 - direction
	star16 - direction
	phenomenon17 - direction
	star18 - direction
	phenomenon19 - direction
	phenomenon20 - direction
	phenomenon21 - direction
	planet22 - direction
	phenomenon23 - direction
	planet24 - direction
	planet25 - direction
	planet26 - direction
	star27 - direction
	star28 - direction
	star29 - direction
)
(:init
	(supports instrument0 image4)
	(supports instrument0 infrared3)
	(supports instrument0 spectrograph2)
	(calibration_target instrument0 groundstation9)
	(calibration_target instrument0 star4)
	(calibration_target instrument0 star1)
	(supports instrument1 spectrograph1)
	(supports instrument1 image4)
	(supports instrument1 image0)
	(calibration_target instrument1 groundstation9)
	(calibration_target instrument1 groundstation7)
	(supports instrument2 image0)
	(calibration_target instrument2 star6)
	(supports instrument3 spectrograph1)
	(calibration_target instrument3 groundstation3)
	(calibration_target instrument3 star6)
	(supports instrument4 image0)
	(supports instrument4 spectrograph2)
	(supports instrument4 image4)
	(calibration_target instrument4 groundstation7)
	(calibration_target instrument4 groundstation9)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 groundstation9)
	(supports instrument5 infrared3)
	(calibration_target instrument5 groundstation8)
	(calibration_target instrument5 star6)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 star18)
	(supports instrument6 image4)
	(calibration_target instrument6 star1)
	(supports instrument7 spectrograph1)
	(supports instrument7 infrared3)
	(calibration_target instrument7 groundstation3)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 groundstation7)
	(supports instrument8 spectrograph1)
	(supports instrument8 infrared3)
	(calibration_target instrument8 star6)
	(calibration_target instrument8 star1)
	(calibration_target instrument8 groundstation5)
	(supports instrument9 infrared3)
	(supports instrument9 image0)
	(calibration_target instrument9 star6)
	(calibration_target instrument9 groundstation9)
	(supports instrument10 infrared3)
	(calibration_target instrument10 groundstation8)
	(calibration_target instrument10 star4)
	(supports instrument11 image0)
	(supports instrument11 spectrograph1)
	(calibration_target instrument11 groundstation2)
	(calibration_target instrument11 groundstation3)
	(calibration_target instrument11 groundstation5)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 planet13)
	(supports instrument12 spectrograph2)
	(supports instrument12 image4)
	(supports instrument12 image0)
	(calibration_target instrument12 groundstation2)
	(calibration_target instrument12 groundstation5)
	(supports instrument13 infrared3)
	(supports instrument13 spectrograph1)
	(calibration_target instrument13 groundstation7)
	(calibration_target instrument13 groundstation3)
	(calibration_target instrument13 groundstation8)
	(supports instrument14 infrared3)
	(supports instrument14 spectrograph1)
	(supports instrument14 image0)
	(calibration_target instrument14 groundstation8)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(power_avail satellite4)
	(pointing satellite4 star10)
)
(:goal (and
	(pointing satellite0 groundstation9)
	(pointing satellite3 star4)
	(pointing satellite4 phenomenon14)
	(have_image star10 spectrograph2)
	(have_image planet11 infrared3)
	(have_image star12 infrared3)
	(have_image planet13 image0)
	(have_image phenomenon14 infrared3)
	(have_image planet15 spectrograph1)
	(have_image star16 image0)
	(have_image phenomenon17 image0)
	(have_image star18 spectrograph1)
	(have_image phenomenon19 spectrograph1)
	(have_image phenomenon20 image0)
	(have_image planet22 spectrograph1)
	(have_image phenomenon23 infrared3)
	(have_image planet24 image4)
	(have_image planet25 spectrograph2)
	(have_image planet26 spectrograph1)
	(have_image star27 spectrograph1)
	(have_image star28 spectrograph2)
	(have_image star29 image4)
))
(:metric minimize (total-time))

)
