(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite3 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite4 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	image4 - mode
	image0 - mode
	infrared3 - mode
	spectrograph1 - mode
	spectrograph2 - mode
	groundstation2 - direction
	star6 - direction
	groundstation9 - direction
	groundstation0 - direction
	groundstation3 - direction
	groundstation11 - direction
	star10 - direction
	groundstation5 - direction
	star1 - direction
	star4 - direction
	groundstation7 - direction
	groundstation8 - direction
	planet12 - direction
	star13 - direction
	phenomenon14 - direction
	star15 - direction
	phenomenon16 - direction
	phenomenon17 - direction
	star18 - direction
	star19 - direction
	star20 - direction
	phenomenon21 - direction
	star22 - direction
	phenomenon23 - direction
	phenomenon24 - direction
	planet25 - direction
	phenomenon26 - direction
	planet27 - direction
	star28 - direction
	planet29 - direction
	planet30 - direction
	planet31 - direction
	phenomenon32 - direction
	planet33 - direction
)
(:init
	(supports instrument0 image4)
	(calibration_target instrument0 star10)
	(calibration_target instrument0 groundstation5)
	(calibration_target instrument0 groundstation7)
	(supports instrument1 image0)
	(supports instrument1 image4)
	(supports instrument1 infrared3)
	(calibration_target instrument1 star10)
	(calibration_target instrument1 groundstation7)
	(calibration_target instrument1 star6)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 star4)
	(supports instrument2 image4)
	(supports instrument2 image0)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 groundstation2)
	(calibration_target instrument2 star6)
	(calibration_target instrument2 groundstation11)
	(calibration_target instrument2 groundstation5)
	(supports instrument3 spectrograph2)
	(supports instrument3 spectrograph1)
	(calibration_target instrument3 star6)
	(calibration_target instrument3 groundstation8)
	(supports instrument4 image0)
	(supports instrument4 spectrograph1)
	(supports instrument4 image4)
	(calibration_target instrument4 groundstation5)
	(calibration_target instrument4 groundstation7)
	(calibration_target instrument4 star10)
	(calibration_target instrument4 groundstation8)
	(supports instrument5 spectrograph2)
	(supports instrument5 infrared3)
	(calibration_target instrument5 groundstation0)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 phenomenon23)
	(supports instrument6 spectrograph2)
	(supports instrument6 image4)
	(supports instrument6 infrared3)
	(calibration_target instrument6 groundstation0)
	(calibration_target instrument6 star4)
	(supports instrument7 infrared3)
	(calibration_target instrument7 star10)
	(calibration_target instrument7 groundstation2)
	(calibration_target instrument7 groundstation0)
	(calibration_target instrument7 star4)
	(supports instrument8 spectrograph2)
	(calibration_target instrument8 star10)
	(calibration_target instrument8 groundstation9)
	(supports instrument9 image4)
	(supports instrument9 spectrograph2)
	(calibration_target instrument9 groundstation3)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(power_avail satellite2)
	(pointing satellite2 planet29)
	(supports instrument10 infrared3)
	(calibration_target instrument10 star10)
	(calibration_target instrument10 groundstation3)
	(supports instrument11 spectrograph1)
	(supports instrument11 image0)
	(supports instrument11 image4)
	(calibration_target instrument11 groundstation9)
	(supports instrument12 spectrograph2)
	(calibration_target instrument12 groundstation9)
	(calibration_target instrument12 groundstation5)
	(calibration_target instrument12 star6)
	(calibration_target instrument12 groundstation2)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(power_avail satellite3)
	(pointing satellite3 star1)
	(supports instrument13 spectrograph1)
	(supports instrument13 spectrograph2)
	(supports instrument13 image0)
	(calibration_target instrument13 star10)
	(supports instrument14 spectrograph2)
	(calibration_target instrument14 groundstation0)
	(supports instrument15 spectrograph1)
	(supports instrument15 image0)
	(supports instrument15 spectrograph2)
	(calibration_target instrument15 groundstation11)
	(calibration_target instrument15 star1)
	(calibration_target instrument15 groundstation3)
	(supports instrument16 spectrograph1)
	(supports instrument16 infrared3)
	(calibration_target instrument16 groundstation5)
	(calibration_target instrument16 star10)
	(calibration_target instrument16 groundstation8)
	(supports instrument17 spectrograph2)
	(calibration_target instrument17 groundstation8)
	(calibration_target instrument17 groundstation7)
	(calibration_target instrument17 star4)
	(calibration_target instrument17 star1)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(power_avail satellite4)
	(pointing satellite4 phenomenon21)
)
(:goal (and
	(pointing satellite2 phenomenon17)
	(pointing satellite3 phenomenon14)
	(pointing satellite4 phenomenon26)
	(have_image planet12 spectrograph1)
	(have_image star13 infrared3)
	(have_image phenomenon14 spectrograph2)
	(have_image star15 image0)
	(have_image phenomenon16 infrared3)
	(have_image phenomenon17 image4)
	(have_image star18 infrared3)
	(have_image star19 infrared3)
	(have_image star20 spectrograph2)
	(have_image phenomenon21 image0)
	(have_image star22 image4)
	(have_image phenomenon24 infrared3)
	(have_image planet25 image4)
	(have_image phenomenon26 spectrograph1)
	(have_image planet27 spectrograph1)
	(have_image star28 spectrograph1)
	(have_image planet29 infrared3)
	(have_image planet30 image0)
	(have_image planet31 image4)
	(have_image phenomenon32 spectrograph2)
	(have_image planet33 infrared3)
))
(:metric minimize (total-time))

)
