(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite1 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite2 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite3 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite4 - satellite
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	satellite5 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	satellite6 - satellite
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	thermograph7 - mode
	thermograph5 - mode
	spectrograph1 - mode
	thermograph6 - mode
	infrared3 - mode
	spectrograph2 - mode
	image4 - mode
	image0 - mode
	star5 - direction
	groundstation10 - direction
	groundstation16 - direction
	star7 - direction
	star18 - direction
	groundstation15 - direction
	star11 - direction
	star13 - direction
	star0 - direction
	star1 - direction
	groundstation4 - direction
	star9 - direction
	groundstation2 - direction
	star6 - direction
	star17 - direction
	groundstation14 - direction
	groundstation19 - direction
	groundstation8 - direction
	star12 - direction
	groundstation3 - direction
	phenomenon20 - direction
	phenomenon21 - direction
	planet22 - direction
	star23 - direction
	phenomenon24 - direction
	planet25 - direction
	planet26 - direction
	planet27 - direction
	planet28 - direction
	phenomenon29 - direction
	planet30 - direction
	star31 - direction
	phenomenon32 - direction
	phenomenon33 - direction
	star34 - direction
	planet35 - direction
	phenomenon36 - direction
	phenomenon37 - direction
	phenomenon38 - direction
	phenomenon39 - direction
	phenomenon40 - direction
	star41 - direction
	planet42 - direction
	planet43 - direction
	planet44 - direction
	phenomenon45 - direction
	phenomenon46 - direction
	planet47 - direction
	planet48 - direction
	star49 - direction
)
(:init
	(supports instrument0 thermograph6)
	(calibration_target instrument0 star12)
	(calibration_target instrument0 star18)
	(calibration_target instrument0 star7)
	(calibration_target instrument0 star17)
	(calibration_target instrument0 star11)
	(calibration_target instrument0 groundstation4)
	(supports instrument1 image0)
	(calibration_target instrument1 groundstation2)
	(calibration_target instrument1 star5)
	(supports instrument2 image0)
	(supports instrument2 infrared3)
	(calibration_target instrument2 groundstation8)
	(supports instrument3 thermograph5)
	(supports instrument3 thermograph7)
	(calibration_target instrument3 star17)
	(calibration_target instrument3 star1)
	(calibration_target instrument3 groundstation10)
	(calibration_target instrument3 star11)
	(supports instrument4 thermograph6)
	(supports instrument4 spectrograph1)
	(supports instrument4 thermograph5)
	(calibration_target instrument4 star12)
	(calibration_target instrument4 groundstation10)
	(calibration_target instrument4 groundstation19)
	(calibration_target instrument4 star17)
	(supports instrument5 thermograph7)
	(calibration_target instrument5 groundstation15)
	(calibration_target instrument5 star17)
	(calibration_target instrument5 star1)
	(calibration_target instrument5 star11)
	(supports instrument6 spectrograph1)
	(supports instrument6 infrared3)
	(supports instrument6 image0)
	(calibration_target instrument6 groundstation8)
	(calibration_target instrument6 groundstation14)
	(calibration_target instrument6 star11)
	(calibration_target instrument6 groundstation3)
	(calibration_target instrument6 star18)
	(calibration_target instrument6 groundstation10)
	(supports instrument7 image0)
	(supports instrument7 spectrograph1)
	(supports instrument7 spectrograph2)
	(calibration_target instrument7 groundstation2)
	(calibration_target instrument7 groundstation19)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(power_avail satellite0)
	(pointing satellite0 planet30)
	(supports instrument8 infrared3)
	(calibration_target instrument8 groundstation14)
	(calibration_target instrument8 groundstation19)
	(supports instrument9 image0)
	(supports instrument9 spectrograph2)
	(calibration_target instrument9 star5)
	(calibration_target instrument9 groundstation2)
	(calibration_target instrument9 groundstation10)
	(calibration_target instrument9 groundstation14)
	(supports instrument10 thermograph6)
	(supports instrument10 thermograph7)
	(calibration_target instrument10 star17)
	(calibration_target instrument10 groundstation3)
	(calibration_target instrument10 groundstation10)
	(calibration_target instrument10 star18)
	(calibration_target instrument10 groundstation4)
	(supports instrument11 thermograph7)
	(calibration_target instrument11 star9)
	(calibration_target instrument11 star5)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(power_avail satellite1)
	(pointing satellite1 star9)
	(supports instrument12 thermograph5)
	(calibration_target instrument12 groundstation10)
	(calibration_target instrument12 groundstation15)
	(calibration_target instrument12 star13)
	(calibration_target instrument12 groundstation8)
	(calibration_target instrument12 star5)
	(supports instrument13 thermograph7)
	(calibration_target instrument13 star18)
	(supports instrument14 thermograph5)
	(supports instrument14 image4)
	(supports instrument14 image0)
	(calibration_target instrument14 star18)
	(calibration_target instrument14 groundstation15)
	(calibration_target instrument14 groundstation4)
	(supports instrument15 infrared3)
	(supports instrument15 thermograph7)
	(calibration_target instrument15 groundstation15)
	(calibration_target instrument15 star1)
	(calibration_target instrument15 star6)
	(calibration_target instrument15 groundstation16)
	(supports instrument16 infrared3)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 groundstation16)
	(calibration_target instrument16 star12)
	(calibration_target instrument16 star17)
	(calibration_target instrument16 groundstation10)
	(calibration_target instrument16 groundstation15)
	(supports instrument17 image0)
	(supports instrument17 infrared3)
	(calibration_target instrument17 star18)
	(calibration_target instrument17 groundstation8)
	(calibration_target instrument17 groundstation10)
	(calibration_target instrument17 star11)
	(calibration_target instrument17 groundstation19)
	(supports instrument18 spectrograph1)
	(calibration_target instrument18 groundstation19)
	(calibration_target instrument18 star12)
	(supports instrument19 thermograph5)
	(supports instrument19 spectrograph1)
	(calibration_target instrument19 star6)
	(calibration_target instrument19 groundstation2)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(power_avail satellite2)
	(pointing satellite2 groundstation16)
	(supports instrument20 thermograph5)
	(calibration_target instrument20 groundstation14)
	(calibration_target instrument20 star18)
	(calibration_target instrument20 star13)
	(calibration_target instrument20 star1)
	(calibration_target instrument20 star11)
	(calibration_target instrument20 groundstation15)
	(supports instrument21 infrared3)
	(supports instrument21 thermograph7)
	(supports instrument21 thermograph5)
	(calibration_target instrument21 groundstation14)
	(calibration_target instrument21 star0)
	(calibration_target instrument21 groundstation2)
	(calibration_target instrument21 star18)
	(calibration_target instrument21 star11)
	(supports instrument22 thermograph7)
	(supports instrument22 spectrograph1)
	(calibration_target instrument22 groundstation2)
	(calibration_target instrument22 groundstation10)
	(calibration_target instrument22 star18)
	(calibration_target instrument22 groundstation4)
	(supports instrument23 thermograph6)
	(supports instrument23 image0)
	(supports instrument23 spectrograph2)
	(calibration_target instrument23 star18)
	(supports instrument24 thermograph7)
	(calibration_target instrument24 groundstation3)
	(calibration_target instrument24 groundstation16)
	(calibration_target instrument24 star6)
	(supports instrument25 thermograph5)
	(supports instrument25 image0)
	(supports instrument25 spectrograph2)
	(calibration_target instrument25 groundstation8)
	(calibration_target instrument25 star9)
	(calibration_target instrument25 star6)
	(calibration_target instrument25 groundstation14)
	(calibration_target instrument25 groundstation16)
	(calibration_target instrument25 star17)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(power_avail satellite3)
	(pointing satellite3 phenomenon37)
	(supports instrument26 thermograph6)
	(calibration_target instrument26 groundstation2)
	(calibration_target instrument26 star11)
	(calibration_target instrument26 star13)
	(calibration_target instrument26 groundstation10)
	(calibration_target instrument26 groundstation19)
	(calibration_target instrument26 groundstation3)
	(supports instrument27 image0)
	(supports instrument27 thermograph7)
	(supports instrument27 spectrograph2)
	(calibration_target instrument27 star6)
	(calibration_target instrument27 star17)
	(calibration_target instrument27 star5)
	(calibration_target instrument27 groundstation10)
	(calibration_target instrument27 groundstation3)
	(calibration_target instrument27 star0)
	(supports instrument28 thermograph5)
	(calibration_target instrument28 groundstation8)
	(calibration_target instrument28 groundstation3)
	(calibration_target instrument28 star1)
	(calibration_target instrument28 groundstation2)
	(calibration_target instrument28 groundstation16)
	(supports instrument29 spectrograph2)
	(supports instrument29 thermograph5)
	(calibration_target instrument29 star12)
	(calibration_target instrument29 star1)
	(calibration_target instrument29 star11)
	(calibration_target instrument29 groundstation10)
	(calibration_target instrument29 groundstation8)
	(calibration_target instrument29 groundstation14)
	(supports instrument30 spectrograph1)
	(supports instrument30 image4)
	(calibration_target instrument30 star12)
	(calibration_target instrument30 groundstation16)
	(calibration_target instrument30 groundstation3)
	(calibration_target instrument30 groundstation4)
	(calibration_target instrument30 groundstation19)
	(calibration_target instrument30 star7)
	(supports instrument31 spectrograph1)
	(supports instrument31 thermograph6)
	(calibration_target instrument31 groundstation3)
	(calibration_target instrument31 star7)
	(calibration_target instrument31 star0)
	(calibration_target instrument31 groundstation4)
	(calibration_target instrument31 groundstation15)
	(on_board instrument26 satellite4)
	(on_board instrument27 satellite4)
	(on_board instrument28 satellite4)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(power_avail satellite4)
	(pointing satellite4 groundstation19)
	(supports instrument32 image4)
	(supports instrument32 spectrograph2)
	(calibration_target instrument32 star9)
	(calibration_target instrument32 groundstation2)
	(calibration_target instrument32 groundstation19)
	(calibration_target instrument32 star13)
	(supports instrument33 image0)
	(calibration_target instrument33 groundstation19)
	(supports instrument34 image0)
	(supports instrument34 infrared3)
	(supports instrument34 thermograph7)
	(calibration_target instrument34 groundstation15)
	(calibration_target instrument34 groundstation8)
	(calibration_target instrument34 star18)
	(on_board instrument32 satellite5)
	(on_board instrument33 satellite5)
	(on_board instrument34 satellite5)
	(power_avail satellite5)
	(pointing satellite5 phenomenon20)
	(supports instrument35 image0)
	(calibration_target instrument35 star6)
	(calibration_target instrument35 star11)
	(calibration_target instrument35 star1)
	(supports instrument36 thermograph7)
	(calibration_target instrument36 groundstation8)
	(calibration_target instrument36 groundstation19)
	(supports instrument37 infrared3)
	(supports instrument37 spectrograph1)
	(supports instrument37 thermograph5)
	(calibration_target instrument37 groundstation8)
	(calibration_target instrument37 star1)
	(calibration_target instrument37 star0)
	(calibration_target instrument37 star13)
	(calibration_target instrument37 groundstation14)
	(supports instrument38 infrared3)
	(calibration_target instrument38 groundstation4)
	(calibration_target instrument38 star12)
	(calibration_target instrument38 groundstation8)
	(calibration_target instrument38 star17)
	(calibration_target instrument38 groundstation14)
	(supports instrument39 infrared3)
	(calibration_target instrument39 groundstation8)
	(calibration_target instrument39 groundstation19)
	(calibration_target instrument39 groundstation2)
	(calibration_target instrument39 star12)
	(calibration_target instrument39 groundstation3)
	(calibration_target instrument39 star9)
	(supports instrument40 spectrograph2)
	(supports instrument40 infrared3)
	(supports instrument40 thermograph6)
	(calibration_target instrument40 star17)
	(calibration_target instrument40 star6)
	(supports instrument41 image0)
	(supports instrument41 image4)
	(calibration_target instrument41 groundstation3)
	(calibration_target instrument41 star12)
	(calibration_target instrument41 groundstation8)
	(calibration_target instrument41 groundstation19)
	(calibration_target instrument41 groundstation14)
	(on_board instrument35 satellite6)
	(on_board instrument36 satellite6)
	(on_board instrument37 satellite6)
	(on_board instrument38 satellite6)
	(on_board instrument39 satellite6)
	(on_board instrument40 satellite6)
	(on_board instrument41 satellite6)
	(power_avail satellite6)
	(pointing satellite6 phenomenon29)
)
(:goal (and
	(have_image phenomenon20 spectrograph1)
	(have_image phenomenon20 thermograph6)
	(have_image phenomenon21 thermograph5)
	(have_image planet22 thermograph6)
	(have_image planet22 spectrograph2)
	(have_image star23 spectrograph1)
	(have_image phenomenon24 spectrograph1)
	(have_image planet26 spectrograph1)
	(have_image planet26 infrared3)
	(have_image planet28 image4)
	(have_image planet28 spectrograph1)
	(have_image phenomenon29 thermograph5)
	(have_image planet30 spectrograph2)
	(have_image planet30 infrared3)
	(have_image star31 image0)
	(have_image phenomenon32 thermograph5)
	(have_image phenomenon32 spectrograph2)
	(have_image phenomenon33 spectrograph2)
	(have_image star34 thermograph5)
	(have_image planet35 spectrograph2)
	(have_image phenomenon36 thermograph7)
	(have_image phenomenon36 thermograph5)
	(have_image phenomenon37 thermograph5)
	(have_image phenomenon37 infrared3)
	(have_image phenomenon38 image0)
	(have_image phenomenon38 thermograph6)
	(have_image phenomenon39 thermograph7)
	(have_image phenomenon40 spectrograph2)
	(have_image phenomenon40 thermograph6)
	(have_image star41 infrared3)
	(have_image planet42 spectrograph2)
	(have_image planet43 spectrograph1)
	(have_image planet44 thermograph6)
	(have_image planet44 thermograph5)
	(have_image phenomenon45 thermograph6)
	(have_image phenomenon46 spectrograph1)
	(have_image phenomenon46 thermograph5)
	(have_image planet47 image4)
	(have_image planet48 image4)
	(have_image star49 image0)
))
(:metric minimize (total-time))

)
