(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite1 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite2 - satellite
	instrument10 - instrument
	instrument11 - instrument
	satellite3 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite4 - satellite
	instrument16 - instrument
	instrument17 - instrument
	satellite5 - satellite
	instrument18 - instrument
	instrument19 - instrument
	satellite6 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	spectrograph2 - mode
	image0 - mode
	image4 - mode
	infrared3 - mode
	spectrograph1 - mode
	groundstation13 - direction
	star10 - direction
	groundstation14 - direction
	groundstation8 - direction
	star6 - direction
	groundstation5 - direction
	groundstation0 - direction
	groundstation3 - direction
	groundstation2 - direction
	groundstation9 - direction
	groundstation11 - direction
	star4 - direction
	star1 - direction
	groundstation7 - direction
	groundstation15 - direction
	groundstation12 - direction
	planet16 - direction
	star17 - direction
	phenomenon18 - direction
	star19 - direction
	phenomenon20 - direction
	planet21 - direction
	planet22 - direction
	star23 - direction
	planet24 - direction
	star25 - direction
	planet26 - direction
	star27 - direction
	planet28 - direction
	phenomenon29 - direction
	planet30 - direction
	phenomenon31 - direction
	planet32 - direction
	phenomenon33 - direction
	planet34 - direction
	star35 - direction
	star36 - direction
	phenomenon37 - direction
	planet38 - direction
	star39 - direction
	phenomenon40 - direction
	planet41 - direction
)
(:init
	(supports instrument0 image4)
	(calibration_target instrument0 groundstation5)
	(calibration_target instrument0 groundstation14)
	(calibration_target instrument0 groundstation9)
	(supports instrument1 infrared3)
	(supports instrument1 image4)
	(calibration_target instrument1 groundstation3)
	(calibration_target instrument1 groundstation11)
	(calibration_target instrument1 groundstation7)
	(supports instrument2 spectrograph2)
	(calibration_target instrument2 groundstation14)
	(calibration_target instrument2 star1)
	(calibration_target instrument2 groundstation2)
	(calibration_target instrument2 star6)
	(supports instrument3 image0)
	(calibration_target instrument3 groundstation2)
	(calibration_target instrument3 groundstation9)
	(supports instrument4 image4)
	(supports instrument4 spectrograph1)
	(supports instrument4 spectrograph2)
	(calibration_target instrument4 groundstation0)
	(calibration_target instrument4 groundstation8)
	(calibration_target instrument4 groundstation12)
	(calibration_target instrument4 star6)
	(calibration_target instrument4 groundstation7)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(power_avail satellite0)
	(pointing satellite0 groundstation7)
	(supports instrument5 infrared3)
	(calibration_target instrument5 groundstation13)
	(calibration_target instrument5 groundstation3)
	(supports instrument6 spectrograph1)
	(supports instrument6 image4)
	(calibration_target instrument6 groundstation12)
	(calibration_target instrument6 groundstation15)
	(calibration_target instrument6 groundstation3)
	(calibration_target instrument6 groundstation8)
	(calibration_target instrument6 groundstation5)
	(supports instrument7 spectrograph2)
	(supports instrument7 image0)
	(calibration_target instrument7 groundstation14)
	(calibration_target instrument7 groundstation5)
	(calibration_target instrument7 groundstation11)
	(calibration_target instrument7 star6)
	(supports instrument8 image0)
	(supports instrument8 infrared3)
	(calibration_target instrument8 groundstation2)
	(calibration_target instrument8 groundstation5)
	(calibration_target instrument8 star4)
	(supports instrument9 infrared3)
	(calibration_target instrument9 groundstation0)
	(calibration_target instrument9 groundstation11)
	(calibration_target instrument9 groundstation2)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(power_avail satellite1)
	(pointing satellite1 planet41)
	(supports instrument10 infrared3)
	(supports instrument10 spectrograph1)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 groundstation5)
	(calibration_target instrument10 star10)
	(calibration_target instrument10 groundstation0)
	(calibration_target instrument10 groundstation7)
	(supports instrument11 infrared3)
	(supports instrument11 image4)
	(calibration_target instrument11 groundstation14)
	(calibration_target instrument11 groundstation12)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(power_avail satellite2)
	(pointing satellite2 groundstation9)
	(supports instrument12 spectrograph1)
	(supports instrument12 image0)
	(calibration_target instrument12 star4)
	(calibration_target instrument12 star6)
	(supports instrument13 image0)
	(calibration_target instrument13 groundstation2)
	(calibration_target instrument13 star4)
	(supports instrument14 spectrograph1)
	(calibration_target instrument14 groundstation3)
	(calibration_target instrument14 star1)
	(calibration_target instrument14 groundstation8)
	(calibration_target instrument14 groundstation14)
	(supports instrument15 spectrograph1)
	(supports instrument15 image0)
	(calibration_target instrument15 star6)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(power_avail satellite3)
	(pointing satellite3 phenomenon37)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 groundstation2)
	(calibration_target instrument16 star1)
	(calibration_target instrument16 groundstation5)
	(supports instrument17 image4)
	(supports instrument17 infrared3)
	(supports instrument17 spectrograph2)
	(calibration_target instrument17 groundstation0)
	(calibration_target instrument17 star1)
	(calibration_target instrument17 groundstation9)
	(calibration_target instrument17 groundstation7)
	(calibration_target instrument17 star4)
	(on_board instrument16 satellite4)
	(on_board instrument17 satellite4)
	(power_avail satellite4)
	(pointing satellite4 phenomenon31)
	(supports instrument18 image0)
	(supports instrument18 infrared3)
	(calibration_target instrument18 groundstation9)
	(supports instrument19 image0)
	(supports instrument19 spectrograph2)
	(calibration_target instrument19 groundstation15)
	(calibration_target instrument19 groundstation7)
	(on_board instrument18 satellite5)
	(on_board instrument19 satellite5)
	(power_avail satellite5)
	(pointing satellite5 groundstation15)
	(supports instrument20 infrared3)
	(supports instrument20 image0)
	(calibration_target instrument20 groundstation2)
	(calibration_target instrument20 groundstation7)
	(calibration_target instrument20 groundstation3)
	(supports instrument21 spectrograph1)
	(calibration_target instrument21 groundstation11)
	(calibration_target instrument21 groundstation7)
	(calibration_target instrument21 groundstation9)
	(supports instrument22 spectrograph1)
	(supports instrument22 infrared3)
	(supports instrument22 image4)
	(calibration_target instrument22 groundstation12)
	(calibration_target instrument22 groundstation15)
	(calibration_target instrument22 groundstation7)
	(calibration_target instrument22 star1)
	(calibration_target instrument22 star4)
	(on_board instrument20 satellite6)
	(on_board instrument21 satellite6)
	(on_board instrument22 satellite6)
	(power_avail satellite6)
	(pointing satellite6 groundstation3)
)
(:goal (and
	(pointing satellite1 planet28)
	(pointing satellite4 planet16)
	(pointing satellite5 star17)
	(have_image planet16 infrared3)
	(have_image star17 spectrograph2)
	(have_image phenomenon18 spectrograph1)
	(have_image star19 image4)
	(have_image phenomenon20 spectrograph1)
	(have_image planet21 spectrograph1)
	(have_image planet22 spectrograph2)
	(have_image star23 image0)
	(have_image planet24 spectrograph1)
	(have_image planet26 image0)
	(have_image planet28 image0)
	(have_image phenomenon29 spectrograph2)
	(have_image planet30 image4)
	(have_image phenomenon31 spectrograph2)
	(have_image planet32 image0)
	(have_image planet34 image4)
	(have_image star36 image4)
	(have_image phenomenon37 spectrograph1)
	(have_image planet38 spectrograph2)
	(have_image star39 spectrograph2)
	(have_image phenomenon40 infrared3)
	(have_image planet41 infrared3)
))
(:metric minimize (total-time))

)
