(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite1 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite2 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	satellite3 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite4 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	thermograph10 - mode
	image8 - mode
	image11 - mode
	infrared3 - mode
	image4 - mode
	thermograph7 - mode
	spectrograph1 - mode
	spectrograph9 - mode
	image0 - mode
	thermograph6 - mode
	thermograph5 - mode
	spectrograph2 - mode
	star12 - direction
	star4 - direction
	groundstation7 - direction
	groundstation15 - direction
	groundstation2 - direction
	star13 - direction
	star11 - direction
	star10 - direction
	groundstation9 - direction
	groundstation6 - direction
	groundstation0 - direction
	groundstation5 - direction
	groundstation16 - direction
	groundstation8 - direction
	star3 - direction
	star14 - direction
	star1 - direction
	phenomenon17 - direction
	planet18 - direction
	phenomenon19 - direction
	planet20 - direction
	star21 - direction
	planet22 - direction
	planet23 - direction
	phenomenon24 - direction
	planet25 - direction
	star26 - direction
	planet27 - direction
	planet28 - direction
	phenomenon29 - direction
	star30 - direction
	phenomenon31 - direction
	planet32 - direction
	phenomenon33 - direction
	phenomenon34 - direction
	planet35 - direction
	star36 - direction
	phenomenon37 - direction
	phenomenon38 - direction
	phenomenon39 - direction
	planet40 - direction
	phenomenon41 - direction
	star42 - direction
	star43 - direction
)
(:init
	(supports instrument0 infrared3)
	(calibration_target instrument0 star1)
	(calibration_target instrument0 groundstation15)
	(calibration_target instrument0 groundstation9)
	(supports instrument1 image4)
	(supports instrument1 thermograph7)
	(supports instrument1 thermograph10)
	(calibration_target instrument1 groundstation6)
	(calibration_target instrument1 star10)
	(supports instrument2 spectrograph2)
	(supports instrument2 thermograph6)
	(calibration_target instrument2 star4)
	(calibration_target instrument2 groundstation8)
	(calibration_target instrument2 star11)
	(supports instrument3 image8)
	(supports instrument3 image4)
	(supports instrument3 thermograph5)
	(calibration_target instrument3 groundstation7)
	(calibration_target instrument3 star13)
	(calibration_target instrument3 groundstation16)
	(supports instrument4 infrared3)
	(calibration_target instrument4 groundstation2)
	(calibration_target instrument4 star1)
	(calibration_target instrument4 star13)
	(supports instrument5 thermograph6)
	(supports instrument5 thermograph5)
	(supports instrument5 spectrograph1)
	(calibration_target instrument5 star13)
	(calibration_target instrument5 star11)
	(calibration_target instrument5 star14)
	(calibration_target instrument5 star4)
	(calibration_target instrument5 groundstation0)
	(supports instrument6 thermograph10)
	(supports instrument6 spectrograph9)
	(supports instrument6 spectrograph2)
	(calibration_target instrument6 star4)
	(supports instrument7 image0)
	(supports instrument7 image4)
	(calibration_target instrument7 star1)
	(calibration_target instrument7 star12)
	(calibration_target instrument7 star13)
	(supports instrument8 infrared3)
	(calibration_target instrument8 star3)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(on_board instrument7 satellite0)
	(on_board instrument8 satellite0)
	(power_avail satellite0)
	(pointing satellite0 phenomenon34)
	(supports instrument9 thermograph5)
	(supports instrument9 thermograph7)
	(supports instrument9 image11)
	(calibration_target instrument9 groundstation0)
	(calibration_target instrument9 star10)
	(calibration_target instrument9 groundstation7)
	(calibration_target instrument9 groundstation6)
	(supports instrument10 infrared3)
	(calibration_target instrument10 star1)
	(calibration_target instrument10 groundstation2)
	(calibration_target instrument10 groundstation7)
	(calibration_target instrument10 star3)
	(calibration_target instrument10 star4)
	(supports instrument11 image4)
	(supports instrument11 thermograph5)
	(calibration_target instrument11 groundstation0)
	(calibration_target instrument11 groundstation6)
	(calibration_target instrument11 groundstation16)
	(calibration_target instrument11 groundstation7)
	(calibration_target instrument11 star10)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(power_avail satellite1)
	(pointing satellite1 star26)
	(supports instrument12 thermograph6)
	(supports instrument12 spectrograph9)
	(supports instrument12 image0)
	(calibration_target instrument12 star13)
	(calibration_target instrument12 groundstation15)
	(calibration_target instrument12 star3)
	(calibration_target instrument12 groundstation9)
	(supports instrument13 thermograph10)
	(supports instrument13 image4)
	(supports instrument13 spectrograph2)
	(calibration_target instrument13 star4)
	(supports instrument14 image11)
	(supports instrument14 image0)
	(calibration_target instrument14 groundstation0)
	(calibration_target instrument14 star1)
	(supports instrument15 infrared3)
	(supports instrument15 image4)
	(calibration_target instrument15 groundstation7)
	(supports instrument16 thermograph7)
	(supports instrument16 thermograph6)
	(calibration_target instrument16 groundstation15)
	(calibration_target instrument16 groundstation6)
	(calibration_target instrument16 groundstation7)
	(calibration_target instrument16 groundstation9)
	(supports instrument17 infrared3)
	(supports instrument17 image0)
	(supports instrument17 spectrograph1)
	(calibration_target instrument17 star11)
	(calibration_target instrument17 star10)
	(calibration_target instrument17 star13)
	(calibration_target instrument17 star3)
	(calibration_target instrument17 groundstation15)
	(supports instrument18 image11)
	(supports instrument18 image4)
	(supports instrument18 image0)
	(calibration_target instrument18 groundstation6)
	(on_board instrument12 satellite2)
	(on_board instrument13 satellite2)
	(on_board instrument14 satellite2)
	(on_board instrument15 satellite2)
	(on_board instrument16 satellite2)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(power_avail satellite2)
	(pointing satellite2 planet40)
	(supports instrument19 spectrograph2)
	(supports instrument19 spectrograph1)
	(calibration_target instrument19 star11)
	(calibration_target instrument19 groundstation15)
	(supports instrument20 image11)
	(calibration_target instrument20 star11)
	(calibration_target instrument20 star3)
	(calibration_target instrument20 groundstation16)
	(supports instrument21 infrared3)
	(supports instrument21 image11)
	(supports instrument21 image0)
	(calibration_target instrument21 star10)
	(calibration_target instrument21 star3)
	(calibration_target instrument21 groundstation2)
	(supports instrument22 thermograph7)
	(calibration_target instrument22 star13)
	(calibration_target instrument22 groundstation16)
	(calibration_target instrument22 star1)
	(calibration_target instrument22 star3)
	(calibration_target instrument22 groundstation6)
	(supports instrument23 image8)
	(calibration_target instrument23 groundstation2)
	(calibration_target instrument23 star14)
	(calibration_target instrument23 star3)
	(calibration_target instrument23 groundstation8)
	(supports instrument24 image11)
	(supports instrument24 spectrograph2)
	(supports instrument24 spectrograph9)
	(calibration_target instrument24 groundstation0)
	(calibration_target instrument24 groundstation9)
	(calibration_target instrument24 groundstation8)
	(calibration_target instrument24 groundstation16)
	(supports instrument25 image11)
	(calibration_target instrument25 star11)
	(calibration_target instrument25 groundstation2)
	(calibration_target instrument25 star3)
	(supports instrument26 infrared3)
	(supports instrument26 spectrograph2)
	(supports instrument26 thermograph7)
	(calibration_target instrument26 star3)
	(calibration_target instrument26 star11)
	(calibration_target instrument26 groundstation16)
	(calibration_target instrument26 star13)
	(supports instrument27 spectrograph1)
	(calibration_target instrument27 groundstation16)
	(calibration_target instrument27 groundstation5)
	(supports instrument28 thermograph7)
	(supports instrument28 image4)
	(calibration_target instrument28 star10)
	(calibration_target instrument28 groundstation0)
	(on_board instrument19 satellite3)
	(on_board instrument20 satellite3)
	(on_board instrument21 satellite3)
	(on_board instrument22 satellite3)
	(on_board instrument23 satellite3)
	(on_board instrument24 satellite3)
	(on_board instrument25 satellite3)
	(on_board instrument26 satellite3)
	(on_board instrument27 satellite3)
	(on_board instrument28 satellite3)
	(power_avail satellite3)
	(pointing satellite3 star26)
	(supports instrument29 thermograph6)
	(calibration_target instrument29 star10)
	(calibration_target instrument29 star3)
	(calibration_target instrument29 groundstation6)
	(supports instrument30 spectrograph9)
	(supports instrument30 spectrograph1)
	(calibration_target instrument30 groundstation9)
	(calibration_target instrument30 star10)
	(supports instrument31 thermograph6)
	(supports instrument31 image0)
	(supports instrument31 spectrograph9)
	(calibration_target instrument31 star14)
	(calibration_target instrument31 groundstation6)
	(supports instrument32 thermograph5)
	(calibration_target instrument32 groundstation0)
	(supports instrument33 thermograph6)
	(calibration_target instrument33 star1)
	(calibration_target instrument33 star3)
	(calibration_target instrument33 groundstation8)
	(calibration_target instrument33 groundstation16)
	(calibration_target instrument33 groundstation5)
	(supports instrument34 spectrograph2)
	(supports instrument34 thermograph5)
	(calibration_target instrument34 star1)
	(calibration_target instrument34 star14)
	(on_board instrument29 satellite4)
	(on_board instrument30 satellite4)
	(on_board instrument31 satellite4)
	(on_board instrument32 satellite4)
	(on_board instrument33 satellite4)
	(on_board instrument34 satellite4)
	(power_avail satellite4)
	(pointing satellite4 planet18)
)
(:goal (and
	(pointing satellite0 star10)
	(pointing satellite2 star4)
	(have_image phenomenon17 image8)
	(have_image phenomenon17 thermograph6)
	(have_image phenomenon17 thermograph7)
	(have_image planet18 spectrograph1)
	(have_image planet18 image0)
	(have_image planet18 infrared3)
	(have_image phenomenon19 image11)
	(have_image phenomenon19 image4)
	(have_image planet20 thermograph5)
	(have_image planet20 infrared3)
	(have_image planet20 spectrograph9)
	(have_image planet20 spectrograph1)
	(have_image star21 spectrograph9)
	(have_image star21 thermograph6)
	(have_image star21 infrared3)
	(have_image star21 image4)
	(have_image planet22 infrared3)
	(have_image planet22 spectrograph1)
	(have_image planet23 thermograph7)
	(have_image planet23 spectrograph1)
	(have_image planet23 spectrograph9)
	(have_image phenomenon24 thermograph5)
	(have_image planet25 image11)
	(have_image planet25 image8)
	(have_image planet25 thermograph6)
	(have_image planet25 infrared3)
	(have_image star26 thermograph7)
	(have_image star26 infrared3)
	(have_image star26 thermograph6)
	(have_image planet27 thermograph6)
	(have_image planet27 spectrograph1)
	(have_image planet28 thermograph6)
	(have_image phenomenon29 thermograph5)
	(have_image phenomenon29 thermograph7)
	(have_image star30 image4)
	(have_image planet32 spectrograph9)
	(have_image phenomenon34 thermograph10)
	(have_image phenomenon34 thermograph6)
	(have_image planet35 thermograph10)
	(have_image planet35 thermograph5)
	(have_image planet35 image0)
	(have_image planet35 thermograph7)
	(have_image phenomenon37 thermograph5)
	(have_image phenomenon37 image8)
	(have_image phenomenon38 image4)
	(have_image phenomenon39 spectrograph9)
	(have_image phenomenon39 thermograph7)
	(have_image phenomenon39 spectrograph1)
	(have_image planet40 thermograph7)
	(have_image planet40 image0)
	(have_image phenomenon41 thermograph5)
	(have_image phenomenon41 thermograph6)
	(have_image phenomenon41 thermograph7)
	(have_image phenomenon41 spectrograph2)
	(have_image star42 thermograph6)
	(have_image star43 thermograph7)
	(have_image star43 spectrograph9)
	(have_image star43 image8)
	(have_image star43 spectrograph1)
))
(:metric minimize (total-time))

)
