(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite6 - satellite
	instrument14 - instrument
	instrument15 - instrument
	infrared3 - mode
	spectrograph1 - mode
	image4 - mode
	image0 - mode
	spectrograph2 - mode
	star10 - direction
	groundstation12 - direction
	groundstation16 - direction
	groundstation0 - direction
	star1 - direction
	groundstation2 - direction
	groundstation11 - direction
	groundstation13 - direction
	groundstation14 - direction
	groundstation15 - direction
	groundstation5 - direction
	groundstation8 - direction
	star6 - direction
	groundstation3 - direction
	groundstation9 - direction
	groundstation7 - direction
	star4 - direction
	phenomenon17 - direction
	planet18 - direction
	planet19 - direction
	planet20 - direction
	star21 - direction
	planet22 - direction
	phenomenon23 - direction
	star24 - direction
	star25 - direction
	phenomenon26 - direction
	star27 - direction
	star28 - direction
	planet29 - direction
	star30 - direction
	star31 - direction
	planet32 - direction
	phenomenon33 - direction
	phenomenon34 - direction
	planet35 - direction
	planet36 - direction
	planet37 - direction
	phenomenon38 - direction
	star39 - direction
	planet40 - direction
	star41 - direction
	planet42 - direction
	star43 - direction
)
(:init
	(supports instrument0 infrared3)
	(supports instrument0 image0)
	(calibration_target instrument0 groundstation3)
	(supports instrument1 image4)
	(supports instrument1 image0)
	(supports instrument1 infrared3)
	(calibration_target instrument1 star6)
	(calibration_target instrument1 groundstation3)
	(calibration_target instrument1 star4)
	(supports instrument2 image4)
	(calibration_target instrument2 star4)
	(calibration_target instrument2 star1)
	(supports instrument3 spectrograph2)
	(supports instrument3 infrared3)
	(supports instrument3 image0)
	(calibration_target instrument3 groundstation0)
	(calibration_target instrument3 groundstation5)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 planet40)
	(supports instrument4 image4)
	(supports instrument4 image0)
	(supports instrument4 spectrograph2)
	(calibration_target instrument4 groundstation11)
	(calibration_target instrument4 groundstation7)
	(calibration_target instrument4 star1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 groundstation8)
	(supports instrument5 image4)
	(supports instrument5 infrared3)
	(calibration_target instrument5 groundstation7)
	(calibration_target instrument5 groundstation15)
	(calibration_target instrument5 star4)
	(supports instrument6 image0)
	(calibration_target instrument6 groundstation15)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 planet19)
	(supports instrument7 spectrograph1)
	(supports instrument7 image4)
	(supports instrument7 image0)
	(calibration_target instrument7 star6)
	(calibration_target instrument7 groundstation7)
	(calibration_target instrument7 groundstation8)
	(supports instrument8 spectrograph1)
	(supports instrument8 image4)
	(calibration_target instrument8 groundstation11)
	(calibration_target instrument8 groundstation2)
	(calibration_target instrument8 star1)
	(calibration_target instrument8 star4)
	(calibration_target instrument8 groundstation9)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 planet37)
	(supports instrument9 spectrograph1)
	(calibration_target instrument9 star4)
	(calibration_target instrument9 groundstation5)
	(supports instrument10 image0)
	(supports instrument10 spectrograph1)
	(calibration_target instrument10 groundstation7)
	(calibration_target instrument10 star4)
	(calibration_target instrument10 star6)
	(calibration_target instrument10 groundstation13)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 planet19)
	(supports instrument11 infrared3)
	(supports instrument11 spectrograph1)
	(supports instrument11 image0)
	(calibration_target instrument11 groundstation5)
	(calibration_target instrument11 star6)
	(calibration_target instrument11 groundstation13)
	(supports instrument12 spectrograph1)
	(supports instrument12 image0)
	(calibration_target instrument12 groundstation15)
	(calibration_target instrument12 groundstation14)
	(supports instrument13 image4)
	(calibration_target instrument13 groundstation3)
	(calibration_target instrument13 groundstation9)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(on_board instrument13 satellite5)
	(power_avail satellite5)
	(pointing satellite5 planet35)
	(supports instrument14 image0)
	(supports instrument14 image4)
	(supports instrument14 spectrograph1)
	(calibration_target instrument14 star6)
	(calibration_target instrument14 groundstation8)
	(calibration_target instrument14 groundstation5)
	(supports instrument15 spectrograph2)
	(calibration_target instrument15 star4)
	(calibration_target instrument15 groundstation7)
	(calibration_target instrument15 groundstation9)
	(calibration_target instrument15 groundstation3)
	(on_board instrument14 satellite6)
	(on_board instrument15 satellite6)
	(power_avail satellite6)
	(pointing satellite6 star10)
)
(:goal (and
	(pointing satellite0 groundstation9)
	(pointing satellite1 groundstation12)
	(pointing satellite4 star31)
	(have_image phenomenon17 spectrograph2)
	(have_image planet18 image4)
	(have_image planet19 spectrograph2)
	(have_image planet20 spectrograph1)
	(have_image star21 image4)
	(have_image planet22 spectrograph1)
	(have_image phenomenon23 image4)
	(have_image star24 image4)
	(have_image star25 infrared3)
	(have_image phenomenon26 image0)
	(have_image star28 spectrograph2)
	(have_image planet29 image4)
	(have_image star30 image4)
	(have_image star31 infrared3)
	(have_image phenomenon33 image4)
	(have_image planet35 image0)
	(have_image planet36 spectrograph1)
	(have_image planet37 image0)
	(have_image phenomenon38 spectrograph2)
	(have_image star39 spectrograph1)
	(have_image planet40 image4)
	(have_image star41 spectrograph1)
	(have_image planet42 spectrograph1)
	(have_image star43 image4)
))
(:metric minimize (total-time))

)
