(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite3 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite4 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	image4 - mode
	spectrograph2 - mode
	spectrograph1 - mode
	image0 - mode
	thermograph5 - mode
	thermograph6 - mode
	infrared3 - mode
	groundstation13 - direction
	groundstation7 - direction
	groundstation3 - direction
	star12 - direction
	groundstation0 - direction
	star11 - direction
	star2 - direction
	groundstation4 - direction
	groundstation1 - direction
	groundstation10 - direction
	groundstation6 - direction
	groundstation5 - direction
	star8 - direction
	star9 - direction
	phenomenon14 - direction
	star15 - direction
	planet16 - direction
	star17 - direction
	planet18 - direction
	planet19 - direction
	star20 - direction
	phenomenon21 - direction
	phenomenon22 - direction
	planet23 - direction
	phenomenon24 - direction
	phenomenon25 - direction
	planet26 - direction
	phenomenon27 - direction
	star28 - direction
	phenomenon29 - direction
	phenomenon30 - direction
	star31 - direction
	planet32 - direction
	planet33 - direction
	star34 - direction
	star35 - direction
	planet36 - direction
	phenomenon37 - direction
)
(:init
	(supports instrument0 image0)
	(supports instrument0 thermograph6)
	(calibration_target instrument0 groundstation0)
	(calibration_target instrument0 groundstation4)
	(calibration_target instrument0 groundstation7)
	(supports instrument1 thermograph5)
	(supports instrument1 image0)
	(supports instrument1 spectrograph1)
	(calibration_target instrument1 groundstation4)
	(calibration_target instrument1 groundstation6)
	(calibration_target instrument1 groundstation7)
	(calibration_target instrument1 groundstation1)
	(supports instrument2 thermograph5)
	(supports instrument2 spectrograph1)
	(supports instrument2 infrared3)
	(calibration_target instrument2 groundstation7)
	(calibration_target instrument2 star2)
	(calibration_target instrument2 groundstation10)
	(calibration_target instrument2 star11)
	(supports instrument3 image0)
	(supports instrument3 spectrograph1)
	(supports instrument3 infrared3)
	(calibration_target instrument3 groundstation1)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 star11)
	(supports instrument4 thermograph5)
	(calibration_target instrument4 star2)
	(calibration_target instrument4 star12)
	(calibration_target instrument4 star11)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 groundstation1)
	(supports instrument5 spectrograph2)
	(calibration_target instrument5 groundstation1)
	(calibration_target instrument5 star11)
	(supports instrument6 image0)
	(supports instrument6 thermograph6)
	(supports instrument6 spectrograph1)
	(calibration_target instrument6 groundstation6)
	(calibration_target instrument6 groundstation5)
	(calibration_target instrument6 groundstation7)
	(supports instrument7 image0)
	(calibration_target instrument7 groundstation7)
	(calibration_target instrument7 star11)
	(calibration_target instrument7 star12)
	(calibration_target instrument7 star9)
	(supports instrument8 image0)
	(calibration_target instrument8 groundstation4)
	(calibration_target instrument8 groundstation10)
	(calibration_target instrument8 star9)
	(calibration_target instrument8 star8)
	(supports instrument9 thermograph5)
	(calibration_target instrument9 star11)
	(supports instrument10 image4)
	(supports instrument10 infrared3)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 groundstation3)
	(calibration_target instrument10 groundstation0)
	(supports instrument11 image0)
	(supports instrument11 thermograph6)
	(supports instrument11 thermograph5)
	(calibration_target instrument11 groundstation1)
	(calibration_target instrument11 star8)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(on_board instrument11 satellite2)
	(power_avail satellite2)
	(pointing satellite2 planet32)
	(supports instrument12 thermograph6)
	(supports instrument12 spectrograph2)
	(calibration_target instrument12 star9)
	(calibration_target instrument12 groundstation0)
	(calibration_target instrument12 star12)
	(supports instrument13 spectrograph2)
	(supports instrument13 thermograph5)
	(supports instrument13 thermograph6)
	(calibration_target instrument13 groundstation6)
	(calibration_target instrument13 groundstation4)
	(calibration_target instrument13 groundstation0)
	(supports instrument14 image4)
	(calibration_target instrument14 groundstation0)
	(supports instrument15 spectrograph2)
	(supports instrument15 image4)
	(supports instrument15 image0)
	(calibration_target instrument15 groundstation10)
	(calibration_target instrument15 star11)
	(calibration_target instrument15 groundstation6)
	(supports instrument16 infrared3)
	(calibration_target instrument16 groundstation4)
	(calibration_target instrument16 star2)
	(supports instrument17 spectrograph2)
	(calibration_target instrument17 star9)
	(calibration_target instrument17 groundstation6)
	(on_board instrument12 satellite3)
	(on_board instrument13 satellite3)
	(on_board instrument14 satellite3)
	(on_board instrument15 satellite3)
	(on_board instrument16 satellite3)
	(on_board instrument17 satellite3)
	(power_avail satellite3)
	(pointing satellite3 planet33)
	(supports instrument18 infrared3)
	(supports instrument18 spectrograph1)
	(supports instrument18 thermograph5)
	(calibration_target instrument18 groundstation1)
	(supports instrument19 image0)
	(supports instrument19 spectrograph1)
	(supports instrument19 thermograph6)
	(calibration_target instrument19 groundstation5)
	(calibration_target instrument19 groundstation6)
	(calibration_target instrument19 groundstation10)
	(supports instrument20 thermograph5)
	(calibration_target instrument20 star9)
	(supports instrument21 infrared3)
	(supports instrument21 thermograph6)
	(calibration_target instrument21 star9)
	(calibration_target instrument21 star8)
	(on_board instrument18 satellite4)
	(on_board instrument19 satellite4)
	(on_board instrument20 satellite4)
	(on_board instrument21 satellite4)
	(power_avail satellite4)
	(pointing satellite4 star15)
)
(:goal (and
	(pointing satellite0 phenomenon37)
	(pointing satellite1 planet36)
	(pointing satellite2 star11)
	(have_image phenomenon14 thermograph6)
	(have_image star15 thermograph5)
	(have_image planet16 image0)
	(have_image star17 thermograph6)
	(have_image planet19 spectrograph2)
	(have_image star20 infrared3)
	(have_image phenomenon21 thermograph5)
	(have_image phenomenon21 thermograph6)
	(have_image phenomenon22 spectrograph1)
	(have_image planet23 thermograph5)
	(have_image phenomenon24 thermograph5)
	(have_image phenomenon25 image4)
	(have_image phenomenon25 infrared3)
	(have_image planet26 infrared3)
	(have_image planet26 image4)
	(have_image phenomenon27 image0)
	(have_image star28 image0)
	(have_image star28 image4)
	(have_image phenomenon29 infrared3)
	(have_image phenomenon29 spectrograph1)
	(have_image phenomenon30 thermograph5)
	(have_image planet32 image0)
	(have_image planet32 infrared3)
	(have_image planet33 spectrograph1)
	(have_image planet33 spectrograph2)
	(have_image star34 spectrograph1)
	(have_image star35 spectrograph2)
	(have_image planet36 spectrograph2)
	(have_image phenomenon37 spectrograph2)
))
(:metric minimize (total-time))

)
