(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite1 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite2 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite3 - satellite
	instrument29 - instrument
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	satellite4 - satellite
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	instrument38 - instrument
	instrument39 - instrument
	instrument40 - instrument
	instrument41 - instrument
	instrument42 - instrument
	instrument43 - instrument
	instrument44 - instrument
	instrument45 - instrument
	instrument46 - instrument
	instrument47 - instrument
	instrument48 - instrument
	instrument49 - instrument
	thermograph12 - mode
	image8 - mode
	spectrograph13 - mode
	spectrograph16 - mode
	spectrograph2 - mode
	spectrograph9 - mode
	thermograph6 - mode
	infrared15 - mode
	image11 - mode
	spectrograph1 - mode
	thermograph10 - mode
	infrared14 - mode
	image0 - mode
	thermograph7 - mode
	image4 - mode
	thermograph5 - mode
	infrared3 - mode
	star15 - direction
	groundstation18 - direction
	groundstation3 - direction
	groundstation6 - direction
	groundstation11 - direction
	groundstation16 - direction
	groundstation12 - direction
	groundstation0 - direction
	groundstation8 - direction
	star14 - direction
	star7 - direction
	groundstation13 - direction
	star9 - direction
	star4 - direction
	star2 - direction
	groundstation17 - direction
	star10 - direction
	groundstation1 - direction
	groundstation5 - direction
	phenomenon19 - direction
	star20 - direction
	planet21 - direction
	phenomenon22 - direction
	star23 - direction
	planet24 - direction
	phenomenon25 - direction
	phenomenon26 - direction
	planet27 - direction
	star28 - direction
	phenomenon29 - direction
	planet30 - direction
	planet31 - direction
	phenomenon32 - direction
	planet33 - direction
	star34 - direction
	planet35 - direction
	planet36 - direction
	planet37 - direction
	star38 - direction
	star39 - direction
	star40 - direction
	planet41 - direction
	planet42 - direction
	star43 - direction
	planet44 - direction
	star45 - direction
	planet46 - direction
	star47 - direction
)
(:init
	(supports instrument0 infrared14)
	(supports instrument0 image0)
	(supports instrument0 thermograph12)
	(calibration_target instrument0 groundstation16)
	(calibration_target instrument0 star15)
	(calibration_target instrument0 star10)
	(supports instrument1 spectrograph13)
	(supports instrument1 thermograph12)
	(calibration_target instrument1 groundstation6)
	(calibration_target instrument1 groundstation17)
	(calibration_target instrument1 star14)
	(calibration_target instrument1 groundstation13)
	(supports instrument2 infrared15)
	(calibration_target instrument2 groundstation18)
	(calibration_target instrument2 groundstation17)
	(calibration_target instrument2 star7)
	(calibration_target instrument2 star2)
	(calibration_target instrument2 groundstation5)
	(supports instrument3 infrared14)
	(calibration_target instrument3 groundstation12)
	(calibration_target instrument3 groundstation3)
	(calibration_target instrument3 star15)
	(calibration_target instrument3 groundstation17)
	(calibration_target instrument3 groundstation5)
	(supports instrument4 spectrograph1)
	(supports instrument4 image4)
	(supports instrument4 infrared15)
	(calibration_target instrument4 groundstation17)
	(calibration_target instrument4 groundstation0)
	(calibration_target instrument4 groundstation6)
	(calibration_target instrument4 groundstation13)
	(calibration_target instrument4 groundstation12)
	(calibration_target instrument4 groundstation3)
	(supports instrument5 thermograph12)
	(supports instrument5 spectrograph1)
	(calibration_target instrument5 star4)
	(calibration_target instrument5 groundstation8)
	(supports instrument6 thermograph10)
	(supports instrument6 thermograph6)
	(supports instrument6 thermograph12)
	(calibration_target instrument6 groundstation0)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(on_board instrument4 satellite0)
	(on_board instrument5 satellite0)
	(on_board instrument6 satellite0)
	(power_avail satellite0)
	(pointing satellite0 groundstation17)
	(supports instrument7 infrared15)
	(supports instrument7 image11)
	(calibration_target instrument7 star4)
	(calibration_target instrument7 groundstation12)
	(supports instrument8 thermograph5)
	(supports instrument8 infrared3)
	(supports instrument8 thermograph6)
	(calibration_target instrument8 groundstation16)
	(calibration_target instrument8 groundstation0)
	(calibration_target instrument8 groundstation11)
	(supports instrument9 thermograph10)
	(supports instrument9 image0)
	(supports instrument9 spectrograph1)
	(calibration_target instrument9 groundstation3)
	(calibration_target instrument9 groundstation16)
	(calibration_target instrument9 star14)
	(calibration_target instrument9 star15)
	(supports instrument10 thermograph12)
	(supports instrument10 image8)
	(calibration_target instrument10 star2)
	(calibration_target instrument10 groundstation0)
	(calibration_target instrument10 groundstation1)
	(calibration_target instrument10 groundstation3)
	(supports instrument11 infrared3)
	(supports instrument11 image11)
	(calibration_target instrument11 groundstation6)
	(calibration_target instrument11 star14)
	(calibration_target instrument11 groundstation17)
	(calibration_target instrument11 star9)
	(supports instrument12 thermograph10)
	(supports instrument12 infrared3)
	(supports instrument12 thermograph7)
	(calibration_target instrument12 groundstation6)
	(calibration_target instrument12 star9)
	(calibration_target instrument12 groundstation5)
	(calibration_target instrument12 groundstation11)
	(supports instrument13 image8)
	(supports instrument13 thermograph5)
	(supports instrument13 infrared3)
	(calibration_target instrument13 groundstation11)
	(calibration_target instrument13 groundstation8)
	(calibration_target instrument13 groundstation6)
	(supports instrument14 spectrograph13)
	(supports instrument14 infrared15)
	(supports instrument14 spectrograph2)
	(calibration_target instrument14 groundstation6)
	(supports instrument15 thermograph10)
	(calibration_target instrument15 star7)
	(calibration_target instrument15 star4)
	(calibration_target instrument15 groundstation1)
	(supports instrument16 image4)
	(supports instrument16 infrared3)
	(supports instrument16 image11)
	(calibration_target instrument16 star15)
	(calibration_target instrument16 star10)
	(calibration_target instrument16 groundstation1)
	(calibration_target instrument16 groundstation5)
	(calibration_target instrument16 star4)
	(calibration_target instrument16 groundstation13)
	(on_board instrument7 satellite1)
	(on_board instrument8 satellite1)
	(on_board instrument9 satellite1)
	(on_board instrument10 satellite1)
	(on_board instrument11 satellite1)
	(on_board instrument12 satellite1)
	(on_board instrument13 satellite1)
	(on_board instrument14 satellite1)
	(on_board instrument15 satellite1)
	(on_board instrument16 satellite1)
	(power_avail satellite1)
	(pointing satellite1 star7)
	(supports instrument17 thermograph5)
	(calibration_target instrument17 groundstation6)
	(calibration_target instrument17 groundstation17)
	(calibration_target instrument17 star14)
	(calibration_target instrument17 groundstation11)
	(calibration_target instrument17 groundstation3)
	(calibration_target instrument17 groundstation13)
	(supports instrument18 thermograph10)
	(supports instrument18 spectrograph2)
	(supports instrument18 image8)
	(calibration_target instrument18 groundstation1)
	(calibration_target instrument18 star4)
	(calibration_target instrument18 groundstation12)
	(calibration_target instrument18 groundstation11)
	(calibration_target instrument18 groundstation13)
	(calibration_target instrument18 star2)
	(supports instrument19 thermograph12)
	(calibration_target instrument19 star15)
	(calibration_target instrument19 groundstation13)
	(calibration_target instrument19 star9)
	(calibration_target instrument19 star2)
	(calibration_target instrument19 groundstation5)
	(supports instrument20 image11)
	(supports instrument20 thermograph12)
	(calibration_target instrument20 groundstation16)
	(calibration_target instrument20 star9)
	(calibration_target instrument20 groundstation6)
	(calibration_target instrument20 groundstation11)
	(calibration_target instrument20 star15)
	(calibration_target instrument20 star10)
	(supports instrument21 spectrograph1)
	(supports instrument21 infrared14)
	(calibration_target instrument21 groundstation16)
	(calibration_target instrument21 groundstation5)
	(calibration_target instrument21 groundstation13)
	(calibration_target instrument21 groundstation8)
	(calibration_target instrument21 star14)
	(calibration_target instrument21 groundstation18)
	(supports instrument22 spectrograph1)
	(supports instrument22 image0)
	(calibration_target instrument22 groundstation13)
	(calibration_target instrument22 groundstation18)
	(calibration_target instrument22 groundstation17)
	(calibration_target instrument22 groundstation8)
	(calibration_target instrument22 groundstation0)
	(supports instrument23 spectrograph9)
	(supports instrument23 image8)
	(calibration_target instrument23 groundstation18)
	(calibration_target instrument23 groundstation11)
	(calibration_target instrument23 star2)
	(calibration_target instrument23 star14)
	(calibration_target instrument23 groundstation5)
	(supports instrument24 infrared3)
	(calibration_target instrument24 groundstation17)
	(calibration_target instrument24 star10)
	(calibration_target instrument24 groundstation12)
	(calibration_target instrument24 groundstation6)
	(calibration_target instrument24 star4)
	(calibration_target instrument24 groundstation11)
	(supports instrument25 spectrograph13)
	(supports instrument25 spectrograph16)
	(calibration_target instrument25 groundstation6)
	(calibration_target instrument25 groundstation11)
	(calibration_target instrument25 groundstation5)
	(calibration_target instrument25 star9)
	(supports instrument26 thermograph6)
	(supports instrument26 spectrograph16)
	(supports instrument26 thermograph10)
	(calibration_target instrument26 groundstation16)
	(supports instrument27 spectrograph1)
	(supports instrument27 image11)
	(supports instrument27 image4)
	(calibration_target instrument27 groundstation8)
	(calibration_target instrument27 star9)
	(calibration_target instrument27 star10)
	(calibration_target instrument27 star15)
	(calibration_target instrument27 groundstation11)
	(supports instrument28 image4)
	(supports instrument28 image0)
	(supports instrument28 spectrograph9)
	(calibration_target instrument28 star4)
	(on_board instrument17 satellite2)
	(on_board instrument18 satellite2)
	(on_board instrument19 satellite2)
	(on_board instrument20 satellite2)
	(on_board instrument21 satellite2)
	(on_board instrument22 satellite2)
	(on_board instrument23 satellite2)
	(on_board instrument24 satellite2)
	(on_board instrument25 satellite2)
	(on_board instrument26 satellite2)
	(on_board instrument27 satellite2)
	(on_board instrument28 satellite2)
	(power_avail satellite2)
	(pointing satellite2 groundstation3)
	(supports instrument29 image4)
	(calibration_target instrument29 star15)
	(supports instrument30 infrared3)
	(calibration_target instrument30 groundstation3)
	(calibration_target instrument30 groundstation0)
	(calibration_target instrument30 star4)
	(calibration_target instrument30 groundstation8)
	(calibration_target instrument30 star9)
	(supports instrument31 spectrograph1)
	(supports instrument31 spectrograph9)
	(supports instrument31 image4)
	(calibration_target instrument31 groundstation5)
	(calibration_target instrument31 groundstation3)
	(supports instrument32 spectrograph2)
	(calibration_target instrument32 groundstation17)
	(calibration_target instrument32 groundstation16)
	(calibration_target instrument32 star15)
	(calibration_target instrument32 groundstation11)
	(supports instrument33 spectrograph9)
	(supports instrument33 image4)
	(supports instrument33 thermograph6)
	(calibration_target instrument33 groundstation3)
	(calibration_target instrument33 star2)
	(calibration_target instrument33 star7)
	(calibration_target instrument33 groundstation0)
	(calibration_target instrument33 star9)
	(on_board instrument29 satellite3)
	(on_board instrument30 satellite3)
	(on_board instrument31 satellite3)
	(on_board instrument32 satellite3)
	(on_board instrument33 satellite3)
	(power_avail satellite3)
	(pointing satellite3 groundstation3)
	(supports instrument34 spectrograph1)
	(calibration_target instrument34 star9)
	(calibration_target instrument34 groundstation12)
	(calibration_target instrument34 star15)
	(supports instrument35 spectrograph1)
	(supports instrument35 thermograph5)
	(calibration_target instrument35 star7)
	(supports instrument36 image4)
	(supports instrument36 image11)
	(calibration_target instrument36 star14)
	(calibration_target instrument36 star9)
	(calibration_target instrument36 groundstation13)
	(calibration_target instrument36 groundstation8)
	(calibration_target instrument36 groundstation6)
	(calibration_target instrument36 groundstation17)
	(supports instrument37 image0)
	(supports instrument37 infrared3)
	(calibration_target instrument37 groundstation6)
	(calibration_target instrument37 star10)
	(supports instrument38 thermograph6)
	(supports instrument38 image4)
	(calibration_target instrument38 groundstation17)
	(calibration_target instrument38 groundstation12)
	(calibration_target instrument38 groundstation0)
	(calibration_target instrument38 groundstation1)
	(supports instrument39 thermograph6)
	(supports instrument39 spectrograph1)
	(supports instrument39 image4)
	(calibration_target instrument39 star14)
	(calibration_target instrument39 groundstation3)
	(calibration_target instrument39 groundstation1)
	(calibration_target instrument39 groundstation18)
	(supports instrument40 image0)
	(supports instrument40 thermograph10)
	(calibration_target instrument40 groundstation1)
	(calibration_target instrument40 star2)
	(calibration_target instrument40 star14)
	(calibration_target instrument40 groundstation8)
	(supports instrument41 infrared15)
	(supports instrument41 image0)
	(supports instrument41 spectrograph1)
	(calibration_target instrument41 star10)
	(calibration_target instrument41 groundstation12)
	(calibration_target instrument41 groundstation1)
	(calibration_target instrument41 groundstation16)
	(calibration_target instrument41 groundstation0)
	(calibration_target instrument41 groundstation6)
	(supports instrument42 image4)
	(supports instrument42 infrared3)
	(calibration_target instrument42 groundstation5)
	(calibration_target instrument42 groundstation13)
	(supports instrument43 thermograph5)
	(calibration_target instrument43 groundstation16)
	(calibration_target instrument43 star2)
	(calibration_target instrument43 groundstation11)
	(supports instrument44 spectrograph1)
	(supports instrument44 image11)
	(calibration_target instrument44 groundstation12)
	(supports instrument45 infrared14)
	(supports instrument45 thermograph10)
	(calibration_target instrument45 star14)
	(calibration_target instrument45 groundstation8)
	(calibration_target instrument45 groundstation0)
	(supports instrument46 thermograph7)
	(calibration_target instrument46 groundstation13)
	(calibration_target instrument46 star7)
	(supports instrument47 thermograph7)
	(supports instrument47 image0)
	(calibration_target instrument47 star4)
	(calibration_target instrument47 star9)
	(supports instrument48 thermograph5)
	(supports instrument48 image4)
	(calibration_target instrument48 groundstation1)
	(calibration_target instrument48 star10)
	(calibration_target instrument48 groundstation17)
	(calibration_target instrument48 star2)
	(supports instrument49 infrared3)
	(calibration_target instrument49 groundstation5)
	(on_board instrument34 satellite4)
	(on_board instrument35 satellite4)
	(on_board instrument36 satellite4)
	(on_board instrument37 satellite4)
	(on_board instrument38 satellite4)
	(on_board instrument39 satellite4)
	(on_board instrument40 satellite4)
	(on_board instrument41 satellite4)
	(on_board instrument42 satellite4)
	(on_board instrument43 satellite4)
	(on_board instrument44 satellite4)
	(on_board instrument45 satellite4)
	(on_board instrument46 satellite4)
	(on_board instrument47 satellite4)
	(on_board instrument48 satellite4)
	(on_board instrument49 satellite4)
	(power_avail satellite4)
	(pointing satellite4 planet36)
)
(:goal (and
	(pointing satellite1 star47)
	(have_image phenomenon19 spectrograph2)
	(have_image phenomenon19 image11)
	(have_image phenomenon19 thermograph10)
	(have_image phenomenon19 thermograph12)
	(have_image phenomenon19 infrared14)
	(have_image star20 thermograph6)
	(have_image star20 spectrograph2)
	(have_image star20 image0)
	(have_image phenomenon22 thermograph5)
	(have_image star23 image4)
	(have_image star23 infrared14)
	(have_image star23 spectrograph1)
	(have_image phenomenon25 spectrograph16)
	(have_image phenomenon25 spectrograph13)
	(have_image phenomenon25 image11)
	(have_image phenomenon25 spectrograph9)
	(have_image phenomenon26 spectrograph9)
	(have_image planet27 thermograph7)
	(have_image planet27 thermograph5)
	(have_image planet27 spectrograph2)
	(have_image star28 infrared14)
	(have_image star28 image4)
	(have_image star28 thermograph10)
	(have_image phenomenon29 infrared15)
	(have_image phenomenon29 spectrograph2)
	(have_image phenomenon29 spectrograph1)
	(have_image phenomenon29 image11)
	(have_image planet30 thermograph7)
	(have_image planet30 spectrograph9)
	(have_image planet30 thermograph5)
	(have_image planet31 thermograph7)
	(have_image planet31 image0)
	(have_image planet31 spectrograph1)
	(have_image planet31 spectrograph13)
	(have_image planet31 image11)
	(have_image phenomenon32 spectrograph2)
	(have_image phenomenon32 infrared15)
	(have_image phenomenon32 image0)
	(have_image phenomenon32 thermograph6)
	(have_image planet33 thermograph5)
	(have_image planet33 infrared15)
	(have_image star34 spectrograph16)
	(have_image planet35 spectrograph13)
	(have_image planet35 image0)
	(have_image planet35 image4)
	(have_image planet35 infrared3)
	(have_image planet36 infrared3)
	(have_image planet36 thermograph12)
	(have_image planet37 infrared3)
	(have_image planet37 thermograph10)
	(have_image planet37 spectrograph1)
	(have_image planet37 image8)
	(have_image planet37 spectrograph13)
	(have_image star38 infrared14)
	(have_image star39 spectrograph13)
	(have_image star39 image11)
	(have_image star39 image4)
	(have_image star40 image8)
	(have_image star40 spectrograph9)
	(have_image star40 thermograph7)
	(have_image star40 infrared15)
	(have_image planet41 spectrograph2)
	(have_image planet41 spectrograph9)
	(have_image planet41 infrared3)
	(have_image planet41 thermograph5)
	(have_image planet42 spectrograph9)
	(have_image star43 thermograph6)
	(have_image planet44 spectrograph13)
	(have_image planet44 image4)
	(have_image star45 thermograph6)
	(have_image star45 spectrograph16)
	(have_image planet46 spectrograph13)
	(have_image planet46 image4)
	(have_image planet46 image0)
	(have_image planet46 thermograph12)
	(have_image planet46 infrared14)
	(have_image star47 image0)
	(have_image star47 thermograph6)
	(have_image star47 image4)
	(have_image star47 image11)
))
(:metric minimize (total-time))

)
