(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	satellite2 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	thermograph7 - mode
	image0 - mode
	spectrograph1 - mode
	infrared3 - mode
	image4 - mode
	thermograph5 - mode
	thermograph6 - mode
	spectrograph2 - mode
	star1 - direction
	star11 - direction
	star5 - direction
	groundstation4 - direction
	groundstation8 - direction
	star9 - direction
	groundstation3 - direction
	star12 - direction
	groundstation2 - direction
	star6 - direction
	star13 - direction
	groundstation14 - direction
	star7 - direction
	groundstation10 - direction
	star0 - direction
	planet15 - direction
	star16 - direction
	star17 - direction
	phenomenon18 - direction
	planet19 - direction
	star20 - direction
	planet21 - direction
	phenomenon22 - direction
	planet23 - direction
	planet24 - direction
	phenomenon25 - direction
	planet26 - direction
	planet27 - direction
	star28 - direction
	star29 - direction
	star30 - direction
	star31 - direction
	star32 - direction
	planet33 - direction
	star34 - direction
	star35 - direction
	star36 - direction
	phenomenon37 - direction
	planet38 - direction
	star39 - direction
)
(:init
	(supports instrument0 image0)
	(calibration_target instrument0 groundstation2)
	(calibration_target instrument0 star13)
	(calibration_target instrument0 groundstation3)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 phenomenon37)
	(supports instrument1 thermograph7)
	(supports instrument1 infrared3)
	(calibration_target instrument1 groundstation10)
	(calibration_target instrument1 star6)
	(on_board instrument1 satellite1)
	(power_avail satellite1)
	(pointing satellite1 groundstation14)
	(supports instrument2 thermograph7)
	(calibration_target instrument2 star9)
	(calibration_target instrument2 groundstation2)
	(calibration_target instrument2 star1)
	(calibration_target instrument2 groundstation4)
	(calibration_target instrument2 groundstation10)
	(supports instrument3 thermograph7)
	(supports instrument3 spectrograph2)
	(supports instrument3 spectrograph1)
	(calibration_target instrument3 star12)
	(supports instrument4 spectrograph1)
	(supports instrument4 spectrograph2)
	(supports instrument4 image4)
	(calibration_target instrument4 star0)
	(calibration_target instrument4 groundstation8)
	(calibration_target instrument4 star7)
	(calibration_target instrument4 star5)
	(supports instrument5 image4)
	(supports instrument5 spectrograph2)
	(calibration_target instrument5 star7)
	(calibration_target instrument5 star5)
	(calibration_target instrument5 star6)
	(calibration_target instrument5 star11)
	(supports instrument6 image0)
	(supports instrument6 infrared3)
	(calibration_target instrument6 groundstation8)
	(calibration_target instrument6 star6)
	(calibration_target instrument6 groundstation4)
	(calibration_target instrument6 groundstation10)
	(on_board instrument2 satellite2)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 planet21)
	(supports instrument7 spectrograph2)
	(calibration_target instrument7 star6)
	(calibration_target instrument7 star9)
	(supports instrument8 image0)
	(supports instrument8 infrared3)
	(calibration_target instrument8 groundstation3)
	(supports instrument9 spectrograph1)
	(supports instrument9 infrared3)
	(calibration_target instrument9 star12)
	(supports instrument10 infrared3)
	(calibration_target instrument10 groundstation2)
	(calibration_target instrument10 groundstation10)
	(calibration_target instrument10 star12)
	(supports instrument11 thermograph6)
	(supports instrument11 thermograph5)
	(supports instrument11 image4)
	(calibration_target instrument11 star7)
	(calibration_target instrument11 groundstation14)
	(calibration_target instrument11 star13)
	(calibration_target instrument11 star6)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 star16)
	(supports instrument12 spectrograph2)
	(calibration_target instrument12 star0)
	(calibration_target instrument12 groundstation10)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 planet26)
)
(:goal (and
	(have_image planet15 thermograph5)
	(have_image planet15 image4)
	(have_image star16 spectrograph1)
	(have_image star17 spectrograph2)
	(have_image phenomenon18 image0)
	(have_image planet19 image4)
	(have_image planet19 image0)
	(have_image star20 spectrograph2)
	(have_image planet21 image0)
	(have_image planet21 thermograph6)
	(have_image phenomenon22 spectrograph1)
	(have_image planet23 image4)
	(have_image planet23 thermograph5)
	(have_image planet24 infrared3)
	(have_image planet24 thermograph5)
	(have_image phenomenon25 spectrograph2)
	(have_image phenomenon25 thermograph6)
	(have_image planet26 thermograph7)
	(have_image planet26 image4)
	(have_image star29 thermograph7)
	(have_image star29 spectrograph1)
	(have_image star30 spectrograph1)
	(have_image star31 thermograph6)
	(have_image star31 thermograph7)
	(have_image star32 image4)
	(have_image planet33 infrared3)
	(have_image planet33 thermograph6)
	(have_image star35 thermograph6)
	(have_image star35 spectrograph2)
	(have_image phenomenon37 spectrograph2)
	(have_image planet38 infrared3)
	(have_image star39 spectrograph2)
))
(:metric minimize (total-time))

)
