Warnings encountered when parsing Domain/Problem File

Errors: 0, warnings: 1
/home/kpb20194/otpl/problems/rovers/domain.pddl: line: 48: Warning: Undeclared requirement :duration-inequalities 
Number of literals: 148
Constructing lookup tables: [10%] [20%] [30%] [40%] [50%] [60%] [70%] [80%] [90%] [100%]
Post filtering unreachable actions:  [10%] [20%] [30%] [40%] [50%] [60%] [70%] [80%] [90%] [100%]
Seeing if metric is defined in terms of task vars or a minimal value of makespan
- Yes it is
Recognised a monotonic-change-induced limit on -1.000*<special>
- Must be >=  the metric
[01;31mLooking for achievers for goal index 0, fact (communicated_soil_data waypoint7) with fID 128[00m
 (communicate_soil_data rover0 general waypoint7 waypoint0 waypoint2) (communicate_soil_data rover1 general waypoint7 waypoint0 waypoint2) (communicate_soil_data rover2 general waypoint7 waypoint0 waypoint2) (communicate_soil_data rover3 general waypoint7 waypoint0 waypoint2) (communicate_soil_data rover0 general waypoint7 waypoint1 waypoint2) (communicate_soil_data rover1 general waypoint7 waypoint1 waypoint2) (communicate_soil_data rover2 general waypoint7 waypoint1 waypoint2) (communicate_soil_data rover3 general waypoint7 waypoint1 waypoint2) (communicate_soil_data rover0 general waypoint7 waypoint4 waypoint2) (communicate_soil_data rover1 general waypoint7 waypoint4 waypoint2) (communicate_soil_data rover2 general waypoint7 waypoint4 waypoint2) (communicate_soil_data rover3 general waypoint7 waypoint4 waypoint2) (communicate_soil_data rover0 general waypoint7 waypoint5 waypoint2) (communicate_soil_data rover2 general waypoint7 waypoint5 waypoint2) (communicate_soil_data rover3 general waypoint7 waypoint5 waypoint2) (communicate_soil_data rover0 general waypoint7 waypoint6 waypoint2) (communicate_soil_data rover1 general waypoint7 waypoint6 waypoint2) (communicate_soil_data rover2 general waypoint7 waypoint6 waypoint2) (communicate_soil_data rover3 general waypoint7 waypoint6 waypoint2) (communicate_soil_data rover0 general waypoint7 waypoint7 waypoint2) (communicate_soil_data rover1 general waypoint7 waypoint7 waypoint2) (communicate_soil_data rover2 general waypoint7 waypoint7 waypoint2) (communicate_soil_data rover3 general waypoint7 waypoint7 waypoint2) (communicate_soil_data rover0 general waypoint7 waypoint8 waypoint2) (communicate_soil_data rover1 general waypoint7 waypoint8 waypoint2) (communicate_soil_data rover2 general waypoint7 waypoint8 waypoint2) (communicate_soil_data rover3 general waypoint7 waypoint8 waypoint2)
[01;34mFor limits: literal goal index 0, fact (communicated_soil_data waypoint7), could be achieved by operator (communicate_soil_data rover0 general waypoint7 waypoint0 waypoint2), which has other interesting effects (including one on (available rover0) )[00m
[01;31mLooking for achievers for goal index 1, fact (communicated_soil_data waypoint5) with fID 127[00m
 (communicate_soil_data rover0 general waypoint5 waypoint0 waypoint2) (communicate_soil_data rover2 general waypoint5 waypoint0 waypoint2) (communicate_soil_data rover3 general waypoint5 waypoint0 waypoint2) (communicate_soil_data rover0 general waypoint5 waypoint1 waypoint2) (communicate_soil_data rover2 general waypoint5 waypoint1 waypoint2) (communicate_soil_data rover3 general waypoint5 waypoint1 waypoint2) (communicate_soil_data rover0 general waypoint5 waypoint4 waypoint2) (communicate_soil_data rover2 general waypoint5 waypoint4 waypoint2) (communicate_soil_data rover3 general waypoint5 waypoint4 waypoint2) (communicate_soil_data rover0 general waypoint5 waypoint5 waypoint2) (communicate_soil_data rover2 general waypoint5 waypoint5 waypoint2) (communicate_soil_data rover3 general waypoint5 waypoint5 waypoint2) (communicate_soil_data rover0 general waypoint5 waypoint6 waypoint2) (communicate_soil_data rover2 general waypoint5 waypoint6 waypoint2) (communicate_soil_data rover3 general waypoint5 waypoint6 waypoint2) (communicate_soil_data rover0 general waypoint5 waypoint7 waypoint2) (communicate_soil_data rover2 general waypoint5 waypoint7 waypoint2) (communicate_soil_data rover3 general waypoint5 waypoint7 waypoint2) (communicate_soil_data rover0 general waypoint5 waypoint8 waypoint2) (communicate_soil_data rover2 general waypoint5 waypoint8 waypoint2) (communicate_soil_data rover3 general waypoint5 waypoint8 waypoint2)
[01;34mFor limits: literal goal index 1, fact (communicated_soil_data waypoint5), could be achieved by operator (communicate_soil_data rover0 general waypoint5 waypoint0 waypoint2), which has other interesting effects (including one on (available rover0) )[00m
[01;31mLooking for achievers for goal index 2, fact (communicated_soil_data waypoint2) with fID 125[00m
 (communicate_soil_data rover0 general waypoint2 waypoint0 waypoint2) (communicate_soil_data rover1 general waypoint2 waypoint0 waypoint2) (communicate_soil_data rover2 general waypoint2 waypoint0 waypoint2) (communicate_soil_data rover3 general waypoint2 waypoint0 waypoint2) (communicate_soil_data rover0 general waypoint2 waypoint1 waypoint2) (communicate_soil_data rover1 general waypoint2 waypoint1 waypoint2) (communicate_soil_data rover2 general waypoint2 waypoint1 waypoint2) (communicate_soil_data rover3 general waypoint2 waypoint1 waypoint2) (communicate_soil_data rover0 general waypoint2 waypoint4 waypoint2) (communicate_soil_data rover1 general waypoint2 waypoint4 waypoint2) (communicate_soil_data rover2 general waypoint2 waypoint4 waypoint2) (communicate_soil_data rover3 general waypoint2 waypoint4 waypoint2) (communicate_soil_data rover0 general waypoint2 waypoint5 waypoint2) (communicate_soil_data rover2 general waypoint2 waypoint5 waypoint2) (communicate_soil_data rover3 general waypoint2 waypoint5 waypoint2) (communicate_soil_data rover0 general waypoint2 waypoint6 waypoint2) (communicate_soil_data rover1 general waypoint2 waypoint6 waypoint2) (communicate_soil_data rover2 general waypoint2 waypoint6 waypoint2) (communicate_soil_data rover3 general waypoint2 waypoint6 waypoint2) (communicate_soil_data rover0 general waypoint2 waypoint7 waypoint2) (communicate_soil_data rover1 general waypoint2 waypoint7 waypoint2) (communicate_soil_data rover2 general waypoint2 waypoint7 waypoint2) (communicate_soil_data rover3 general waypoint2 waypoint7 waypoint2) (communicate_soil_data rover0 general waypoint2 waypoint8 waypoint2) (communicate_soil_data rover1 general waypoint2 waypoint8 waypoint2) (communicate_soil_data rover2 general waypoint2 waypoint8 waypoint2) (communicate_soil_data rover3 general waypoint2 waypoint8 waypoint2)
[01;34mFor limits: literal goal index 2, fact (communicated_soil_data waypoint2), could be achieved by operator (communicate_soil_data rover0 general waypoint2 waypoint0 waypoint2), which has other interesting effects (including one on (available rover0) )[00m
[01;31mLooking for achievers for goal index 3, fact (communicated_soil_data waypoint4) with fID 126[00m
 (communicate_soil_data rover0 general waypoint4 waypoint0 waypoint2) (communicate_soil_data rover1 general waypoint4 waypoint0 waypoint2) (communicate_soil_data rover2 general waypoint4 waypoint0 waypoint2) (communicate_soil_data rover3 general waypoint4 waypoint0 waypoint2) (communicate_soil_data rover0 general waypoint4 waypoint1 waypoint2) (communicate_soil_data rover1 general waypoint4 waypoint1 waypoint2) (communicate_soil_data rover2 general waypoint4 waypoint1 waypoint2) (communicate_soil_data rover3 general waypoint4 waypoint1 waypoint2) (communicate_soil_data rover0 general waypoint4 waypoint4 waypoint2) (communicate_soil_data rover1 general waypoint4 waypoint4 waypoint2) (communicate_soil_data rover2 general waypoint4 waypoint4 waypoint2) (communicate_soil_data rover3 general waypoint4 waypoint4 waypoint2) (communicate_soil_data rover0 general waypoint4 waypoint5 waypoint2) (communicate_soil_data rover2 general waypoint4 waypoint5 waypoint2) (communicate_soil_data rover3 general waypoint4 waypoint5 waypoint2) (communicate_soil_data rover0 general waypoint4 waypoint6 waypoint2) (communicate_soil_data rover1 general waypoint4 waypoint6 waypoint2) (communicate_soil_data rover2 general waypoint4 waypoint6 waypoint2) (communicate_soil_data rover3 general waypoint4 waypoint6 waypoint2) (communicate_soil_data rover0 general waypoint4 waypoint7 waypoint2) (communicate_soil_data rover1 general waypoint4 waypoint7 waypoint2) (communicate_soil_data rover2 general waypoint4 waypoint7 waypoint2) (communicate_soil_data rover3 general waypoint4 waypoint7 waypoint2) (communicate_soil_data rover0 general waypoint4 waypoint8 waypoint2) (communicate_soil_data rover1 general waypoint4 waypoint8 waypoint2) (communicate_soil_data rover2 general waypoint4 waypoint8 waypoint2) (communicate_soil_data rover3 general waypoint4 waypoint8 waypoint2)
[01;34mFor limits: literal goal index 3, fact (communicated_soil_data waypoint4), could be achieved by operator (communicate_soil_data rover0 general waypoint4 waypoint0 waypoint2), which has other interesting effects (including one on (available rover0) )[00m
[01;31mLooking for achievers for goal index 4, fact (communicated_rock_data waypoint4) with fID 132[00m
 (communicate_rock_data rover2 general waypoint4 waypoint0 waypoint2) (communicate_rock_data rover3 general waypoint4 waypoint0 waypoint2) (communicate_rock_data rover2 general waypoint4 waypoint1 waypoint2) (communicate_rock_data rover3 general waypoint4 waypoint1 waypoint2) (communicate_rock_data rover2 general waypoint4 waypoint4 waypoint2) (communicate_rock_data rover3 general waypoint4 waypoint4 waypoint2) (communicate_rock_data rover2 general waypoint4 waypoint5 waypoint2) (communicate_rock_data rover3 general waypoint4 waypoint5 waypoint2) (communicate_rock_data rover2 general waypoint4 waypoint6 waypoint2) (communicate_rock_data rover3 general waypoint4 waypoint6 waypoint2) (communicate_rock_data rover2 general waypoint4 waypoint7 waypoint2) (communicate_rock_data rover3 general waypoint4 waypoint7 waypoint2) (communicate_rock_data rover2 general waypoint4 waypoint8 waypoint2) (communicate_rock_data rover3 general waypoint4 waypoint8 waypoint2)
[01;34mFor limits: literal goal index 4, fact (communicated_rock_data waypoint4), could be achieved by operator (communicate_rock_data rover2 general waypoint4 waypoint0 waypoint2), which has other interesting effects (including one on (available rover2) )[00m
[01;31mLooking for achievers for goal index 5, fact (communicated_rock_data waypoint6) with fID 133[00m
 (communicate_rock_data rover2 general waypoint6 waypoint0 waypoint2) (communicate_rock_data rover3 general waypoint6 waypoint0 waypoint2) (communicate_rock_data rover2 general waypoint6 waypoint1 waypoint2) (communicate_rock_data rover3 general waypoint6 waypoint1 waypoint2) (communicate_rock_data rover2 general waypoint6 waypoint4 waypoint2) (communicate_rock_data rover3 general waypoint6 waypoint4 waypoint2) (communicate_rock_data rover2 general waypoint6 waypoint5 waypoint2) (communicate_rock_data rover3 general waypoint6 waypoint5 waypoint2) (communicate_rock_data rover2 general waypoint6 waypoint6 waypoint2) (communicate_rock_data rover3 general waypoint6 waypoint6 waypoint2) (communicate_rock_data rover2 general waypoint6 waypoint7 waypoint2) (communicate_rock_data rover3 general waypoint6 waypoint7 waypoint2) (communicate_rock_data rover2 general waypoint6 waypoint8 waypoint2) (communicate_rock_data rover3 general waypoint6 waypoint8 waypoint2)
[01;34mFor limits: literal goal index 5, fact (communicated_rock_data waypoint6), could be achieved by operator (communicate_rock_data rover2 general waypoint6 waypoint0 waypoint2), which has other interesting effects (including one on (available rover2) )[00m
[01;31mLooking for achievers for goal index 6, fact (communicated_rock_data waypoint7) with fID 134[00m
 (communicate_rock_data rover2 general waypoint7 waypoint0 waypoint2) (communicate_rock_data rover3 general waypoint7 waypoint0 waypoint2) (communicate_rock_data rover2 general waypoint7 waypoint1 waypoint2) (communicate_rock_data rover3 general waypoint7 waypoint1 waypoint2) (communicate_rock_data rover2 general waypoint7 waypoint4 waypoint2) (communicate_rock_data rover3 general waypoint7 waypoint4 waypoint2) (communicate_rock_data rover2 general waypoint7 waypoint5 waypoint2) (communicate_rock_data rover3 general waypoint7 waypoint5 waypoint2) (communicate_rock_data rover2 general waypoint7 waypoint6 waypoint2) (communicate_rock_data rover3 general waypoint7 waypoint6 waypoint2) (communicate_rock_data rover2 general waypoint7 waypoint7 waypoint2) (communicate_rock_data rover3 general waypoint7 waypoint7 waypoint2) (communicate_rock_data rover2 general waypoint7 waypoint8 waypoint2) (communicate_rock_data rover3 general waypoint7 waypoint8 waypoint2)
[01;34mFor limits: literal goal index 6, fact (communicated_rock_data waypoint7), could be achieved by operator (communicate_rock_data rover2 general waypoint7 waypoint0 waypoint2), which has other interesting effects (including one on (available rover2) )[00m
[01;31mLooking for achievers for goal index 7, fact (communicated_rock_data waypoint8) with fID 135[00m
 (communicate_rock_data rover2 general waypoint8 waypoint0 waypoint2) (communicate_rock_data rover3 general waypoint8 waypoint0 waypoint2) (communicate_rock_data rover2 general waypoint8 waypoint1 waypoint2) (communicate_rock_data rover3 general waypoint8 waypoint1 waypoint2) (communicate_rock_data rover2 general waypoint8 waypoint4 waypoint2) (communicate_rock_data rover3 general waypoint8 waypoint4 waypoint2) (communicate_rock_data rover2 general waypoint8 waypoint5 waypoint2) (communicate_rock_data rover3 general waypoint8 waypoint5 waypoint2) (communicate_rock_data rover2 general waypoint8 waypoint6 waypoint2) (communicate_rock_data rover3 general waypoint8 waypoint6 waypoint2) (communicate_rock_data rover2 general waypoint8 waypoint7 waypoint2) (communicate_rock_data rover3 general waypoint8 waypoint7 waypoint2) (communicate_rock_data rover2 general waypoint8 waypoint8 waypoint2) (communicate_rock_data rover3 general waypoint8 waypoint8 waypoint2)
[01;34mFor limits: literal goal index 7, fact (communicated_rock_data waypoint8), could be achieved by operator (communicate_rock_data rover2 general waypoint8 waypoint0 waypoint2), which has other interesting effects (including one on (available rover2) )[00m
[01;31mLooking for achievers for goal index 8, fact (communicated_rock_data waypoint1) with fID 130[00m
 (communicate_rock_data rover2 general waypoint1 waypoint0 waypoint2) (communicate_rock_data rover3 general waypoint1 waypoint0 waypoint2) (communicate_rock_data rover2 general waypoint1 waypoint1 waypoint2) (communicate_rock_data rover3 general waypoint1 waypoint1 waypoint2) (communicate_rock_data rover2 general waypoint1 waypoint4 waypoint2) (communicate_rock_data rover3 general waypoint1 waypoint4 waypoint2) (communicate_rock_data rover2 general waypoint1 waypoint5 waypoint2) (communicate_rock_data rover3 general waypoint1 waypoint5 waypoint2) (communicate_rock_data rover2 general waypoint1 waypoint6 waypoint2) (communicate_rock_data rover3 general waypoint1 waypoint6 waypoint2) (communicate_rock_data rover2 general waypoint1 waypoint7 waypoint2) (communicate_rock_data rover3 general waypoint1 waypoint7 waypoint2) (communicate_rock_data rover2 general waypoint1 waypoint8 waypoint2) (communicate_rock_data rover3 general waypoint1 waypoint8 waypoint2)
[01;34mFor limits: literal goal index 8, fact (communicated_rock_data waypoint1), could be achieved by operator (communicate_rock_data rover2 general waypoint1 waypoint0 waypoint2), which has other interesting effects (including one on (available rover2) )[00m
[01;31mLooking for achievers for goal index 9, fact (communicated_image_data objective3 high_res) with fID 143[00m
 (communicate_image_data rover0 general objective3 high_res waypoint0 waypoint2) (communicate_image_data rover2 general objective3 high_res waypoint0 waypoint2) (communicate_image_data rover3 general objective3 high_res waypoint0 waypoint2) (communicate_image_data rover0 general objective3 high_res waypoint1 waypoint2) (communicate_image_data rover2 general objective3 high_res waypoint1 waypoint2) (communicate_image_data rover3 general objective3 high_res waypoint1 waypoint2) (communicate_image_data rover0 general objective3 high_res waypoint4 waypoint2) (communicate_image_data rover2 general objective3 high_res waypoint4 waypoint2) (communicate_image_data rover3 general objective3 high_res waypoint4 waypoint2) (communicate_image_data rover0 general objective3 high_res waypoint5 waypoint2) (communicate_image_data rover2 general objective3 high_res waypoint5 waypoint2) (communicate_image_data rover3 general objective3 high_res waypoint5 waypoint2) (communicate_image_data rover0 general objective3 high_res waypoint6 waypoint2) (communicate_image_data rover2 general objective3 high_res waypoint6 waypoint2) (communicate_image_data rover3 general objective3 high_res waypoint6 waypoint2) (communicate_image_data rover0 general objective3 high_res waypoint7 waypoint2) (communicate_image_data rover2 general objective3 high_res waypoint7 waypoint2) (communicate_image_data rover3 general objective3 high_res waypoint7 waypoint2) (communicate_image_data rover0 general objective3 high_res waypoint8 waypoint2) (communicate_image_data rover2 general objective3 high_res waypoint8 waypoint2) (communicate_image_data rover3 general objective3 high_res waypoint8 waypoint2)
[01;34mFor limits: literal goal index 9, fact (communicated_image_data objective3 high_res), could be achieved by operator (communicate_image_data rover0 general objective3 high_res waypoint0 waypoint2), which has other interesting effects (including one on (available rover0) )[00m
[01;31mLooking for achievers for goal index 10, fact (communicated_image_data objective1 high_res) with fID 141[00m
 (communicate_image_data rover0 general objective1 high_res waypoint0 waypoint2) (communicate_image_data rover2 general objective1 high_res waypoint0 waypoint2) (communicate_image_data rover3 general objective1 high_res waypoint0 waypoint2) (communicate_image_data rover0 general objective1 high_res waypoint1 waypoint2) (communicate_image_data rover2 general objective1 high_res waypoint1 waypoint2) (communicate_image_data rover3 general objective1 high_res waypoint1 waypoint2) (communicate_image_data rover0 general objective1 high_res waypoint4 waypoint2) (communicate_image_data rover2 general objective1 high_res waypoint4 waypoint2) (communicate_image_data rover3 general objective1 high_res waypoint4 waypoint2) (communicate_image_data rover0 general objective1 high_res waypoint5 waypoint2) (communicate_image_data rover2 general objective1 high_res waypoint5 waypoint2) (communicate_image_data rover3 general objective1 high_res waypoint5 waypoint2) (communicate_image_data rover0 general objective1 high_res waypoint6 waypoint2) (communicate_image_data rover2 general objective1 high_res waypoint6 waypoint2) (communicate_image_data rover3 general objective1 high_res waypoint6 waypoint2) (communicate_image_data rover0 general objective1 high_res waypoint7 waypoint2) (communicate_image_data rover2 general objective1 high_res waypoint7 waypoint2) (communicate_image_data rover3 general objective1 high_res waypoint7 waypoint2) (communicate_image_data rover0 general objective1 high_res waypoint8 waypoint2) (communicate_image_data rover2 general objective1 high_res waypoint8 waypoint2) (communicate_image_data rover3 general objective1 high_res waypoint8 waypoint2)
[01;34mFor limits: literal goal index 10, fact (communicated_image_data objective1 high_res), could be achieved by operator (communicate_image_data rover0 general objective1 high_res waypoint0 waypoint2), which has other interesting effects (including one on (available rover0) )[00m
[01;31mLooking for achievers for goal index 11, fact (communicated_image_data objective2 high_res) with fID 142[00m
 (communicate_image_data rover0 general objective2 high_res waypoint0 waypoint2) (communicate_image_data rover2 general objective2 high_res waypoint0 waypoint2) (communicate_image_data rover3 general objective2 high_res waypoint0 waypoint2) (communicate_image_data rover0 general objective2 high_res waypoint1 waypoint2) (communicate_image_data rover2 general objective2 high_res waypoint1 waypoint2) (communicate_image_data rover3 general objective2 high_res waypoint1 waypoint2) (communicate_image_data rover0 general objective2 high_res waypoint4 waypoint2) (communicate_image_data rover2 general objective2 high_res waypoint4 waypoint2) (communicate_image_data rover3 general objective2 high_res waypoint4 waypoint2) (communicate_image_data rover0 general objective2 high_res waypoint5 waypoint2) (communicate_image_data rover2 general objective2 high_res waypoint5 waypoint2) (communicate_image_data rover3 general objective2 high_res waypoint5 waypoint2) (communicate_image_data rover0 general objective2 high_res waypoint6 waypoint2) (communicate_image_data rover2 general objective2 high_res waypoint6 waypoint2) (communicate_image_data rover3 general objective2 high_res waypoint6 waypoint2) (communicate_image_data rover0 general objective2 high_res waypoint7 waypoint2) (communicate_image_data rover2 general objective2 high_res waypoint7 waypoint2) (communicate_image_data rover3 general objective2 high_res waypoint7 waypoint2) (communicate_image_data rover0 general objective2 high_res waypoint8 waypoint2) (communicate_image_data rover2 general objective2 high_res waypoint8 waypoint2) (communicate_image_data rover3 general objective2 high_res waypoint8 waypoint2)
[01;34mFor limits: literal goal index 11, fact (communicated_image_data objective2 high_res), could be achieved by operator (communicate_image_data rover0 general objective2 high_res waypoint0 waypoint2), which has other interesting effects (including one on (available rover0) )[00m
- Duration of (recharge rover0 waypoint3) is not constant-bounded
Non-constant-bounded duration-dependent effect ((energy rover0) +=15.000*?duration) makes effects on 0 be order-dependent
- Duration of (recharge rover1 waypoint3) is not constant-bounded
Non-constant-bounded duration-dependent effect ((energy rover1) +=20.000*?duration) makes effects on 1 be order-dependent
- Duration of (recharge rover2 waypoint3) is not constant-bounded
Non-constant-bounded duration-dependent effect ((energy rover2) +=12.000*?duration) makes effects on 2 be order-dependent
- Duration of (recharge rover3 waypoint3) is not constant-bounded
Non-constant-bounded duration-dependent effect ((energy rover3) +=16.000*?duration) makes effects on 3 be order-dependent
94% of the ground temporal actions in this problem are compression-safe
Initial heuristic = 43.000, admissible cost estimate 30.004
b (42.000 | 5.000)b (41.000 | 10.000)b (39.000 | 10.000)b (38.000 | 13.001)b (37.000 | 13.001)b (36.000 | 15.000)b (35.000 | 15.000)b (34.000 | 23.002)b (33.000 | 23.002)b (32.000 | 23.002)b (31.000 | 25.002)b (30.000 | 33.003)b (29.000 | 33.003)b (28.000 | 33.003)b (27.000 | 33.003)b (26.000 | 33.003)b (25.000 | 33.004)b (24.000 | 33.004)b (23.000 | 33.004)b (22.000 | 41.005)b (21.000 | 41.005)b (20.000 | 43.004)b (19.000 | 53.004)b (18.000 | 68.006)b (17.000 | 68.006)b (16.000 | 68.006)b (15.000 | 68.006)b (14.000 | 88.008)b (13.000 | 103.009)b (12.000 | 103.009)b (11.000 | 103.009)b (10.000 | 103.009)b (9.000 | 113.010)b (8.000 | 128.011)b (7.000 | 128.011)b (6.000 | 128.011)b (5.000 | 128.011)b (4.000 | 137.014)b (2.000 | 138.012)b (1.000 | 138.012)(G)
; LP calculated the cost

; Plan found with metric 148.013
; Theoretical reachable cost 148.014
; States evaluated so far: 6440
; States pruned based on pre-heuristic cost lower bound: 0
; Time 14.02
0.000: (calibrate rover2 camera0 objective1 waypoint6)  [5.000]
0.000: (sample_soil rover0 rover0store waypoint7)  [10.000]
0.000: (navigate rover3 waypoint3 waypoint8)  [5.000]
0.000: (navigate rover1 waypoint6 waypoint0)  [5.000]
5.001: (sample_rock rover3 rover3store waypoint8)  [8.000]
5.001: (navigate rover1 waypoint0 waypoint2)  [5.000]
5.001: (take_image rover2 waypoint6 objective3 camera0 high_res)  [7.000]
7.002: (calibrate rover2 camera0 objective1 waypoint6)  [5.000]
7.003: (sample_rock rover2 rover2store waypoint6)  [8.000]
10.000: (navigate rover0 waypoint7 waypoint0)  [5.000]
10.002: (sample_soil rover1 rover1store waypoint2)  [10.000]
12.002: (take_image rover2 waypoint6 objective1 camera0 high_res)  [7.000]
13.002: (communicate_rock_data rover3 general waypoint8 waypoint8 waypoint2)  [10.000]
13.002: (drop rover3 rover3store)  [1.000]
14.003: (calibrate rover2 camera0 objective1 waypoint6)  [5.000]
19.003: (navigate rover2 waypoint6 waypoint0)  [5.000]
20.002: (navigate rover1 waypoint2 waypoint0)  [5.000]
23.003: (navigate rover3 waypoint8 waypoint3)  [5.000]
23.003: (communicate_soil_data rover0 general waypoint7 waypoint0 waypoint2)  [10.000]
23.004: (calibrate rover0 camera4 objective1 waypoint0)  [5.000]
24.003: (take_image rover2 waypoint0 objective2 camera0 high_res)  [7.000]
28.004: (navigate rover3 waypoint3 waypoint7)  [5.000]
28.004: (take_image rover0 waypoint0 objective3 camera4 high_res)  [7.000]
30.005: (calibrate rover0 camera4 objective1 waypoint0)  [5.000]
31.003: (navigate rover2 waypoint0 waypoint5)  [5.000]
33.004: (communicate_soil_data rover1 general waypoint2 waypoint0 waypoint2)  [10.000]
33.005: (sample_rock rover3 rover3store waypoint7)  [8.000]
35.003: (drop rover2 rover2store)  [1.000]
35.005: (take_image rover0 waypoint0 objective2 camera4 high_res)  [7.000]
36.004: (sample_soil rover2 rover2store waypoint5)  [10.000]
37.006: (calibrate rover0 camera4 objective1 waypoint0)  [5.000]
41.006: (drop rover3 rover3store)  [1.000]
42.006: (take_image rover0 waypoint0 objective1 camera4 high_res)  [7.000]
43.005: (communicate_rock_data rover3 general waypoint7 waypoint7 waypoint2)  [10.000]
43.005: (navigate rover1 waypoint0 waypoint2)  [5.000]
46.004: (navigate rover2 waypoint5 waypoint0)  [5.000]
46.005: (drop rover2 rover2store)  [1.000]
48.006: (navigate rover1 waypoint2 waypoint4)  [5.000]
53.006: (communicate_image_data rover0 general objective3 high_res waypoint0 waypoint2)  [15.000]
53.006: (navigate rover3 waypoint7 waypoint3)  [5.000]
58.007: (recharge rover3 waypoint3)  [5.000]
63.008: (navigate rover3 waypoint3 waypoint1)  [5.000]
68.007: (communicate_rock_data rover2 general waypoint6 waypoint0 waypoint2)  [10.000]
68.008: (calibrate rover3 camera2 objective1 waypoint1)  [5.000]
73.008: (take_image rover3 waypoint1 objective1 camera2 high_res)  [7.000]
73.009: (sample_rock rover3 rover3store waypoint1)  [8.000]
78.008: (communicate_soil_data rover2 general waypoint5 waypoint0 waypoint2)  [10.000]
81.009: (navigate rover3 waypoint1 waypoint3)  [5.000]
86.010: (navigate rover3 waypoint3 waypoint0)  [5.000]
88.009: (communicate_image_data rover0 general objective2 high_res waypoint0 waypoint2)  [15.000]
103.010: (communicate_rock_data rover3 general waypoint1 waypoint0 waypoint2)  [10.000]
113.011: (communicate_image_data rover0 general objective1 high_res waypoint0 waypoint2)  [15.000]
113.011: (navigate rover3 waypoint0 waypoint4)  [5.000]
117.011: (drop rover3 rover3store)  [1.000]
118.012: (sample_rock rover3 rover3store waypoint4)  [8.000]
126.013: (drop rover3 rover3store)  [1.000]
127.014: (sample_soil rover3 rover3store waypoint4)  [10.000]
128.012: (communicate_rock_data rover3 general waypoint4 waypoint4 waypoint2)  [10.000]
138.013: (communicate_soil_data rover3 general waypoint4 waypoint4 waypoint2)  [10.000]

 * All goal deadlines now no later than 148.013

Resorting to best-first search
Running WA* with W = 5.000, not restarting with goal states
b (42.000 | 5.000)b (41.000 | 5.000)b (40.000 | 5.000)b (39.000 | 10.000)b (39.000 | 5.000)b (38.000 | 13.001)b (38.000 | 10.000)b (37.000 | 13.001)b (36.000 | 15.000)b (36.000 | 13.001)b (35.000 | 15.000)b (34.000 | 23.002)b (33.000 | 23.002)b (32.000 | 33.003)b (31.000 | 33.003)b (30.000 | 33.003)b (29.000 | 48.004)b (28.000 | 65.004)b (27.000 | 80.006)